PYTHON ?= python3
VENV := .venv
VENV_PYTHON := $(VENV)/bin/python

.PHONY: venv lock check

## Create the local environment and install the project with the dev and server extras.
venv:
	$(PYTHON) -m venv $(VENV)
	$(VENV_PYTHON) -m pip install --upgrade pip
	$(VENV_PYTHON) -m pip install -e '.[dev,server]'

## Regenerate requirements.lock from the local environment.
lock: venv
	@{ \
	  printf '# Dependency lock for process-runtime.\n'; \
	  printf '# Python: %s\n' "$$($(VENV_PYTHON) -c 'import platform; print(platform.python_version())')"; \
	  printf '# Generated by: make lock  (%s -m pip freeze --exclude-editable)\n' "$(VENV_PYTHON)"; \
	  printf '# The editable project itself is excluded; CI installs it separately with `pip install -e .`.\n'; \
	  $(VENV_PYTHON) -m pip freeze --exclude-editable; \
	} > requirements.lock

## Lint, format-check, type-check and test.
check:
	PATH="$(CURDIR)/$(VENV)/bin:$$PATH" ./scripts/check.sh
