// M06 WO-6: api.js — URL building, errors, the cache, the raw export's digest, the long poll, and
// readWhole against the server's own views of a document built to reach every expander branch
// (tests/web/fixtures/expander.json, generated by scripts/m06_web_expander_fixture.py from
// `projection.project` + `bound_document`). Every request goes through an injected transport.

import { test } from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";

import {
  ApiError,
  buildRequest,
  createApi,
  isMarker,
  READ_WHOLE_BUDGET,
  ReadError,
} from "../../apps/web/js/api.js";

const FIXTURE = JSON.parse(
  readFileSync(new URL("./fixtures/expander.json", import.meta.url), "utf-8"),
);
const TOKEN = "prt_test-token";

function store(token = TOKEN) {
  let held = token;
  return { get: () => held, clear: () => (held = null), held: () => held };
}

function response(status, body, headers = {}) {
  const bytes = body instanceof Uint8Array ? body : new TextEncoder().encode(JSON.stringify(body));
  return {
    status,
    headers: { get: (name) => headers[name.toLowerCase()] ?? null },
    json: async () => JSON.parse(new TextDecoder().decode(bytes)),
    arrayBuffer: async () => bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.length),
  };
}

// A transport answering `answer(url, init)` and logging each request.
function recorder(answer) {
  const log = [];
  const transport = async (url, init) => {
    log.push({ url, init });
    return answer(url, init, log.length);
  };
  return { log, transport };
}

function query(url) {
  return new URLSearchParams(url.includes("?") ? url.slice(url.indexOf("?") + 1) : "");
}

// The fixture's server: a view per (pointer, cursor), at depth 12 and limit 200 only.
function fixtureServer(fixture = FIXTURE) {
  return recorder((url) => {
    assert.ok(url.startsWith("/v1/revisions/rev-000001?"), url);
    const params = query(url);
    assert.equal(params.get("depth"), String(fixture.depth));
    assert.equal(params.get("limit"), String(fixture.limit));
    const key = `${params.get("pointer")}\n${params.get("cursor") ?? ""}`;
    const view = fixture.responses[key];
    assert.ok(view !== undefined, `no fixture view for ${JSON.stringify(key)}`);
    return response(200, view);
  });
}

test("a GET carries path parameters encoded and the other members as query text", () => {
  const { url, init } = buildRequest(
    "get_artifact",
    { artifact_id: "job-000001/solve-events.json", pointer: "/a b", depth: 12, cursor: null },
    TOKEN,
    "SIGNAL",
  );
  assert.equal(url, "/v1/artifacts/job-000001%2Fsolve-events.json?depth=12&pointer=%2Fa+b");
  assert.deepEqual(init, {
    method: "GET",
    headers: { Authorization: `Bearer ${TOKEN}` },
    cache: "no-store",
    credentials: "omit",
    redirect: "error",
    signal: "SIGNAL",
  });
  const raw = buildRequest("artifact_bytes", { artifact_id: "a/b" }, TOKEN).url;
  assert.equal(raw, "/v1/artifacts/a%2Fb/raw");
  assert.equal(buildRequest("get_project", {}, TOKEN).url, "/v1/project");
  const waited = buildRequest(
    "wait_job",
    { job_id: "job-000001", after_sequence: -1, timeout_s: 20 },
    TOKEN,
  );
  assert.equal(waited.url, "/v1/jobs/job-000001/wait?after_sequence=-1&timeout_s=20");
});

test("a POST carries the other members as a JSON body, never in the URL", () => {
  const body = {
    operation: "solve",
    idempotency_key: "ui-solve-0123456789abcdef0123456789abcdef",
    body: { revision_id: "rev-000001", policy_id: "default" },
  };
  const { url, init } = buildRequest("submit_job", body, TOKEN);
  assert.equal(url, "/v1/jobs");
  assert.equal(init.method, "POST");
  assert.equal(init.headers["Content-Type"], "application/json");
  assert.deepEqual(JSON.parse(init.body), body);
  const validate = buildRequest("validate", { revision_id: "rev-000003", task: "simulation" }, TOKEN);
  assert.equal(validate.url, "/v1/revisions/rev-000003/validate");
  assert.equal(validate.init.body, '{"task":"simulation"}');
  assert.equal(buildRequest("cancel_job", { job_id: "job-000002" }, TOKEN).init.body, "{}");
  assert.ok(!url.includes(TOKEN) && !validate.url.includes(TOKEN));
});

test("buildRequest refuses what the route table does not allow", () => {
  assert.throws(() => buildRequest("no_such_operation", {}, TOKEN), /not an HTTP operation/);
  assert.throws(() => buildRequest("get_job", { job_id: "j", extra: 1 }, TOKEN), /no request member/);
  assert.throws(() => buildRequest("get_job", {}, TOKEN), /needs job_id/);
  assert.throws(
    () => buildRequest("list_jobs", { limit: Number.POSITIVE_INFINITY }, TOKEN),
    /non-finite/,
  );
  assert.throws(() => buildRequest("submit_job", { body: { x: Number.NaN } }, TOKEN), /non-finite/);
  assert.throws(() => buildRequest("list_jobs", { status: { a: 1 } }, TOKEN), /query/);
});

test("a 2xx document is returned; a non-2xx answer is the server's ApiError", async () => {
  const error = { code: "not_found", message: "no such revision", retryable: false, detail: {} };
  const { log, transport } = recorder((url) =>
    url.startsWith("/v1/project") ? response(200, { project_id: "p" }) : response(404, error),
  );
  const api = createApi(transport, store());
  assert.deepEqual(await api.call("get_project"), { project_id: "p" });
  await assert.rejects(api.call("get_job", { job_id: "job-9" }), (raised) => {
    assert.ok(raised instanceof ApiError);
    assert.equal(raised.status, 404);
    assert.deepEqual(raised.document, error);
    return true;
  });
  assert.equal(log.length, 2);
});

test("a 401 clears the stored token; no token means no request", async () => {
  const tokens = store();
  const refused = { code: "unauthenticated", message: "token unknown", retryable: false, detail: {} };
  const { log, transport } = recorder(() => response(401, refused));
  const api = createApi(transport, tokens);
  await assert.rejects(api.call("get_project"), (raised) => raised.status === 401);
  assert.equal(tokens.held(), null);
  await assert.rejects(api.call("get_project"), (raised) => raised.code === "unauthenticated");
  assert.equal(log.length, 1);
});

test("a non-2xx answer without an error document becomes internal_error", async () => {
  const { transport } = recorder(() => ({
    status: 502,
    headers: { get: () => null },
    json: async () => {
      throw new SyntaxError("not JSON");
    },
  }));
  await assert.rejects(createApi(transport, store()).call("get_project"), (raised) => {
    assert.equal(raised.status, 502);
    assert.equal(raised.code, "internal_error");
    return true;
  });
});

test("the cache holds the listed operations and nothing else, never an error", async () => {
  let fail = true;
  const { log, transport } = recorder((url) => {
    if (url.startsWith("/v1/jobs/job-1/result") && fail) {
      fail = false;
      return response(409, { code: "not_ready", message: "running", retryable: true, detail: {} });
    }
    return response(200, { url });
  });
  const api = createApi(transport, store());
  await api.call("diff_revisions", { from_revision: "a", to_revision: "b" });
  await api.call("diff_revisions", { to_revision: "b", from_revision: "a" });
  await api.call("list_jobs", { limit: 5 });
  await api.call("list_jobs", { limit: 5 });
  await assert.rejects(api.call("get_job_result", { job_id: "job-1" }));
  await api.call("get_job_result", { job_id: "job-1" });
  await api.call("get_job_result", { job_id: "job-1" });
  await api.call("get_project");
  await api.call("get_project");
  assert.deepEqual(
    log.map((entry) => entry.url),
    [
      "/v1/revisions/a/diff/b",
      "/v1/jobs?limit=5",
      "/v1/jobs?limit=5",
      "/v1/jobs/job-1/result",
      "/v1/jobs/job-1/result",
      "/v1/project",
      "/v1/project",
    ],
  );
});

test("raw: exact bytes, checked against the registered SHA-256", async () => {
  const bytes = new TextEncoder().encode('{"status":"VERIFIED","checks":[]}\n');
  const sha = createHash("sha256").update(bytes).digest("hex");
  const { log, transport } = recorder(() => response(200, bytes, { "x-content-sha256": sha }));
  const api = createApi(transport, store());
  const read = await api.raw("job-000001/solution-certificate.json", sha);
  assert.deepEqual(Array.from(read.bytes), Array.from(bytes));
  assert.equal(read.digest, "match");
  assert.equal((await api.raw("job-000001/solution-certificate.json", "0".repeat(64))).digest, "mismatch");
  const parsed = await api.rawJson("job-000001/solution-certificate.json", sha);
  assert.deepEqual(parsed.document, { status: "VERIFIED", checks: [] });
  assert.equal(log.length, 1, "the bytes are cached; the digest is checked on every read");
  assert.equal(log[0].url, "/v1/artifacts/job-000001%2Fsolution-certificate.json/raw");
  await assert.rejects(api.call("artifact_bytes", { artifact_id: "x" }), /raw\(\)/);
});

test("raw: without crypto.subtle (an insecure context) the digest is unchecked", async () => {
  const saved = Object.getOwnPropertyDescriptor(globalThis, "crypto");
  Object.defineProperty(globalThis, "crypto", { value: undefined, configurable: true });
  try {
    const { transport } = recorder(() => response(200, new Uint8Array([1, 2, 3])));
    const read = await createApi(transport, store()).raw("a", "0".repeat(64));
    assert.equal(read.digest, "unchecked");
    assert.equal(read.sha256, null);
  } finally {
    Object.defineProperty(globalThis, "crypto", saved);
  }
});

test("readWhole reassembles the document from the server's own views", async () => {
  const server = fixtureServer();
  const api = createApi(server.transport, store());
  const whole = await api.readWhole("get_revision", { revision_id: "rev-000001" });
  assert.deepEqual(whole, FIXTURE.expected);
  const asked = server.log.map(({ url }) => {
    const params = query(url);
    return `${params.get("pointer")}|${params.get("cursor") ?? ""}`;
  });
  assert.ok(asked.length <= READ_WHOLE_BUDGET);
  assert.equal(new Set(asked).size, asked.length, "no view is asked for twice");
  const includes = (entry) => assert.ok(asked.includes(entry), `expected a request for ${entry}`);
  includes("|"); // the root, truncated to fit
  includes("/deep|"); // an object elided below the shown depth
  includes("/long_array|"); // a nested array cut at 20 ...
  includes("/long_array|eyJvZmZzZXQiOjIwMH0"); // ... read whole as a target, paged past 200
  includes("/nested_arrays/0|"); // a nested array of 25 cut at 20 inside an array
  includes("/nested_arrays/1|"); // 21 items: cut
  includes("/wide/a~1b~0c|"); // RFC 6901 escaping of a marker's pointer
  includes("/literal_marker|"); // literal content shaped like a marker: read once, kept
  includes("/literal_tail|"); // the same as an array's last item
  assert.ok(!asked.includes("/nested_arrays/2|"), "20 items are not cut");
  assert.equal(FIXTURE.responses["/flat_wide\n"].truncated, true);
  assert.deepEqual(whole.literal_marker, { $elided: { pointer: "/literal_marker", members: 2 } });
  assert.equal(whole.title, "readWhole fixture �evil");
  // Cached: the second read asks for nothing.
  const before = server.log.length;
  assert.deepEqual(await api.readWhole("get_revision", { revision_id: "rev-000001" }), whole);
  assert.equal(server.log.length, before);
});

test("readWhole refuses a document whose hash changes between views", async () => {
  const changed = structuredClone(FIXTURE);
  changed.responses["/deep\n"].sha256 = "f".repeat(64);
  const api = createApi(fixtureServer(changed).transport, store());
  await assert.rejects(
    api.readWhole("get_revision", { revision_id: "rev-000001" }),
    (raised) => raised instanceof ReadError && /changed while it was read/.test(raised.message),
  );
});

test("readWhole stops at its request budget", async () => {
  const { log, transport } = recorder((url) => {
    const pointer = query(url).get("pointer");
    const next = `${pointer}/x`;
    return response(200, {
      subject_id: "s",
      pointer,
      sha256: "a".repeat(64),
      value: { x: { $elided: { pointer: next, members: 1 } } },
      truncated: false,
      next_cursor: null,
    });
  });
  const api = createApi(transport, store());
  await assert.rejects(
    api.readWhole("inspect_structure", { revision_id: "rev-1" }),
    (raised) => raised instanceof ReadError && /500 requests/.test(raised.message),
  );
  assert.equal(log.length, READ_WHOLE_BUDGET);
  await assert.rejects(api.readWhole("get_revision", { revision_id: "r", depth: 3 }), /sets depth/);
});

test("isMarker recognises exactly the projection's marker of its own pointer", () => {
  assert.ok(isMarker({ $elided: { pointer: "/a", members: 3 } }, "/a"));
  assert.ok(isMarker({ $elided: { pointer: "/a", items: 0 } }, "/a", "items"));
  assert.ok(!isMarker({ $elided: { pointer: "/a", items: 1 } }, "/a", "members"));
  assert.ok(!isMarker({ $elided: { pointer: "/b", members: 3 } }, "/a"));
  assert.ok(!isMarker({ $elided: { pointer: "/a", members: 3 }, other: 1 }, "/a"));
  assert.ok(!isMarker({ $elided: { pointer: "/a", members: 3, items: 1 } }, "/a"));
  assert.ok(!isMarker({ $elided: { pointer: "/a", members: 1.5 } }, "/a"));
  assert.ok(!isMarker({ $elided: { pointer: "/a", members: -1 } }, "/a"));
  assert.ok(!isMarker([{ $elided: { pointer: "/a", members: 1 } }], "/a"));
  assert.ok(!isMarker(null, "/a"));
});

test("followJob waits until the job has ended, advancing after_sequence", async () => {
  const answers = [
    { job: { status: "running" }, events: [{ sequence: 0 }, { sequence: 1 }], ended: false },
    { job: { status: "running" }, events: [], ended: false },
    { job: { status: "completed" }, events: [{ sequence: 2 }], ended: true },
  ];
  const { log, transport } = recorder((url, init, count) => {
    assert.equal(init.signal, "SIGNAL");
    return response(200, answers[count - 1]);
  });
  const seen = [];
  const job = await createApi(transport, store()).followJob("job-000001", {
    signal: "SIGNAL",
    onWait: (waited) => seen.push(waited.events.length),
  });
  assert.deepEqual(job, { status: "completed" });
  assert.deepEqual(seen, [2, 0, 1]);
  assert.deepEqual(
    log.map(({ url }) => query(url).get("after_sequence")),
    ["-1", "1", "1"],
  );
});
