"""K01: the declared backend dependency, and that it installs the bytes P03 audited.

ADR 0003 selected CasADi 3.8.0; ADR 0006 D5.3 makes the per-file SHA-256 record in
`spikes/p03/results/casadi-inventory.json` the audited baseline for that pin, and its Q4 asks
whether mode A's "the audited bytes are the installed bytes" is enforced or merely assumed. These
tests enforce it, which is cheaper than `pip --require-hashes` and checks more: a hash-pinned wheel
proves the download, while this proves what is actually on disk in the environment the gate runs in.

The audit was taken on one platform. A second platform's wheel is a different artifact with its own
inventory (ADR 0003 Q1, owned by K05), so the byte comparison skips rather than fails where the
recorded host does not match — an unaudited platform is an absence of evidence, and reporting it as
a failure would be as wrong as reporting it as a pass.
"""

from __future__ import annotations

import hashlib
import platform
import sys
import tomllib
from pathlib import Path
from typing import Any

import pytest
from conftest import load_json

PIN = "casadi==3.8.0"
AUDIT = "docs/p03-binary-audit.md"


@pytest.fixture(scope="session")
def inventory(repo_root: Path) -> dict[str, Any]:
    loaded = load_json(repo_root / "spikes" / "p03" / "results" / "casadi-inventory.json")
    assert isinstance(loaded, dict)
    return loaded


@pytest.fixture(scope="session")
def installed_casadi() -> Path:
    """Where CasADi actually is in the running interpreter's environment."""
    import casadi  # noqa: PLC0415 - the point of the fixture is to locate the installed package

    return Path(casadi.__file__).resolve().parent


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def test_the_backend_is_declared_as_an_exact_pin(repo_root: Path) -> None:
    """ADR 0006 D5.3. A range would make the audit describe bytes nobody is required to install."""
    with (repo_root / "pyproject.toml").open("rb") as handle:
        project = tomllib.load(handle)
    assert PIN in project["project"]["dependencies"]


def test_the_lock_carries_the_same_pin(repo_root: Path) -> None:
    lock = (repo_root / "requirements.lock").read_text(encoding="utf-8")
    assert PIN in lock.splitlines()


def test_the_installed_version_is_the_audited_one(inventory: dict[str, Any]) -> None:
    import casadi  # noqa: PLC0415

    assert casadi.__version__ == inventory["dist_info"]["declared"]["Version"] == "3.8.0"


def test_the_readme_carries_the_third_party_notice(repo_root: Path) -> None:
    """ADR 0006 D5.1: the obligation the LGPL actually creates, and the one K01 owes."""
    readme = (repo_root / "README.md").read_text(encoding="utf-8")
    for required in ("CasADi", "3.8.0", "LGPL", "casadi/LICENSE/LICENSE.txt", AUDIT):
        assert required in readme, f"README.md lost the ADR 0006 D5.1 notice element {required!r}"


def test_the_installed_bytes_are_the_audited_bytes(
    inventory: dict[str, Any], installed_casadi: Path
) -> None:
    """ADR 0006 D5.3 and Q4: what P03 audited is what this environment actually runs.

    Only `__pycache__` bytecode may differ — CPython writes it on import and embeds the source path
    and mtime, so it is generated by the install rather than shipped in the wheel. It is counted
    rather than skipped silently, the same way `scripts/p03_verify_reproduction.py` counts it.
    """
    host = inventory["host"]
    if (platform.machine(), sys.version_info[:2]) != (
        host["machine"],
        tuple(int(part) for part in host["python"].split(".")[:2]),
    ):
        pytest.skip(
            f"the audit records {host['machine']} / Python {host['python']}; this is "
            f"{platform.machine()} / Python {sys.version_info[0]}.{sys.version_info[1]}. "
            "A second platform's wheel is a different artifact with its own inventory (K05)."
        )

    recorded = {
        entry["path"]: (int(entry["bytes"]), str(entry["sha256"])) for entry in inventory["files"]
    }
    present = {
        str(path.relative_to(installed_casadi))
        for path in installed_casadi.rglob("*")
        if path.is_file() and not path.is_symlink()
    }
    assert not sorted(set(recorded) - present), "the installed package is missing audited files"
    assert not sorted(present - set(recorded)), (
        "the installed package has files the audit never saw"
    )

    differing: list[str] = []
    generated: list[str] = []
    for relative in sorted(set(recorded) & present):
        path = installed_casadi / relative
        size, digest = recorded[relative]
        if path.stat().st_size == size and sha256_of(path) == digest:
            continue
        (
            generated if relative.endswith(".pyc") or "__pycache__/" in relative else differing
        ).append(relative)
    assert not differing, (
        f"{len(differing)} shipped file(s) differ from the P03 audit, e.g. {differing[:5]}. "
        f"The pin no longer installs the audited bytes; re-run the audit before trusting {AUDIT}."
    )


def test_no_object_in_the_metis_closure_is_loaded_by_importing_the_backend(
    inventory: dict[str, Any],
) -> None:
    """ADR 0006 D1.5: a use restriction, not only a redistribution one.

    Importing CasADi must not pull in anything reachable to `libcoinmetis`. This is checked against
    the process's actually-loaded shared objects, not against the recorded `DT_NEEDED` closure,
    because the restriction is about what runs — a plugin `dlopen`ed at import time would satisfy
    the static closure and still violate D1.5.
    """
    import casadi  # noqa: PLC0415,F401 - importing it is the action under test

    maps = Path("/proc/self/maps")
    if not maps.is_file():  # pragma: no cover - non-Linux host
        pytest.skip("this check reads /proc/self/maps")
    loaded = maps.read_text(encoding="utf-8", errors="replace")
    mapped = sorted(
        {line.rsplit("/", 1)[-1] for line in loaded.split() if "/casadi/" in line and ".so" in line}
    )

    # Anti-vacuity: a test that scans an empty map passes for the wrong reason. Importing the
    # backend must actually have mapped it before "nothing forbidden is mapped" means anything.
    assert any(name.startswith("libcasadi") for name in mapped), (
        f"importing casadi mapped no libcasadi object ({mapped}); this check cannot conclude "
        "anything from that, so it fails rather than passing vacuously."
    )

    # The audit predicted this exact set from the static DT_NEEDED closure of `_casadi.so`
    # (docs/p03-binary-audit.md §2.3). Runtime agreeing with it is the stronger statement, and a
    # divergence means a plugin is being pulled in at import time.
    assert set(mapped) <= {"_casadi.so", "libcasadi.so.3.7"}, (
        f"importing casadi mapped {mapped}, beyond the audited import closure "
        "{_casadi.so, libcasadi.so.3.7}. Something is loading a plugin at import time; re-check "
        "reachability against libcoinmetis before this merges (ADR 0006 D5.4)."
    )

    forbidden = [
        name
        for name in ("libcoinmetis", "libcoinmumps", "libipopt", "libsipopt", "libuno", "libbonmin")
        if name in loaded
    ]
    assert not forbidden, (
        f"importing casadi loaded {forbidden}, which is in the METIS 4.0 closure. "
        "ADR 0006 D1.5 forbids any default path from loading it."
    )
