"""ADR 0008 A1 J1–J3, J5: T07's acceptance for the binding items of Amendment 1 C6.

The amendment names four acceptance items for T07's own test module:
(a) `Job` fixtures with 0, 1 and 3 outputs validate, the last mixing kinds;
(b) the lifecycle checker accepts a stream with two output events and a progress event before the
    event that ends the job, and the job's output list afterwards holds the two references in
    order;
(c) a request with an operation outside the enum is rejected, and each enum value has exactly one
    request branch;
(d) each shipped consumer ignores an output and an event of unknown kind without error, and
    recognizes an unknown-kind event that ends the job through J5's member.

Items (b) and (c) are here from W1; item (a) from W4a, whose fixtures are emitted by real jobs
(`scripts/t07_schema_fixtures.py`, R-015). Item (d) needs the shipped consumers and joins this
module with each: the CLI's from W5b; HTTP's and MCP's with W6. The kinds T07 names for (b) are
`output`, `progress` and `ended`, and J5's member is `ends_job` (design note §5.6).
"""

from __future__ import annotations

import dataclasses
from pathlib import Path
from typing import Any, get_args

import pytest
from conftest import REPO_ROOT, load_json
from t07_support import (
    AT,
    COMPLETED,
    JOB_ID,
    LATER,
    completed_solve,
    event,
    job,
    opaque,
    progress,
    ref,
)

from openflowsheet.application.jobs.model import (
    EVENT_KINDS,
    JOB_OPERATIONS,
    JobOperation,
    check_lifecycle,
)
from openflowsheet.application.types import (
    DocumentSchemaError,
    Job,
    JobEvent,
    JobRequest,
    ReproduceBody,
    SolveBody,
    schema_errors,
)

JOB_REQUEST = "job.schema.json#/$defs/job_request"
FIXTURES = REPO_ROOT / "tests" / "fixtures" / "schemas"
#: ADR 0008 A1 (a): a job with 0, 1 and 3 outputs, emitted by real jobs.
JOB_FIXTURES = {
    0: "job/valid/solve_cancelled_while_queued.json",
    1: "job/valid/reproduce_without_rerun.json",
    3: "job/valid/solve_converged.json",
}


def _job_request_schema() -> dict[str, Any]:
    document: dict[str, Any] = load_json(REPO_ROOT / "schemas" / "job.schema.json")
    return document["$defs"]


# ----------------------------------------------------------------------------------- item (a)


@pytest.mark.parametrize(("count", "name"), sorted(JOB_FIXTURES.items()))
def test_a_job_fixtures_with_0_1_and_3_outputs_validate(count: int, name: str) -> None:
    """ADR 0008 A1 J1–J3: each fixture validates against the published (producer) schema, holds
    exactly `count` typed references, and round-trips; the 3-output one mixes kinds."""
    document = load_json(FIXTURES / name)
    assert schema_errors("job.schema.json", document) == []
    job = Job.from_document(document)
    assert job.as_document() == document
    assert len(job.outputs) == count
    kinds = [output.kind for output in job.outputs]
    if count == 3:
        assert kinds == ["solution_certificate", "run_manifest", "replay_bundle"]
        assert len(set(kinds)) == 3
    # J1: no member holds a single certificate, manifest, result or failure bundle.
    assert not {"certificate", "manifest", "result", "failure_bundle"} & set(document)
    assert job.operation == job.request.operation  # J3


def test_a_the_job_schema_puts_no_maximum_on_outputs() -> None:
    outputs = load_json(REPO_ROOT / "schemas" / "job.schema.json")["properties"]["outputs"]
    assert outputs["type"] == "array" and "maxItems" not in outputs


def test_a_one_job_event_fixture_per_producer_kind_validates() -> None:
    names = sorted((FIXTURES / "job_event" / "valid").glob("*.json"))
    documents = [load_json(path) for path in names]
    for document in documents:
        assert schema_errors("job-event.schema.json", document) == []
        assert JobEvent.from_document(document).as_document() == document
    assert {document["kind"] for document in documents} == set(EVENT_KINDS)
    endings = sorted(d["ending"]["status"] for d in documents if d["kind"] == "ended")
    assert endings == ["cancelled", "completed"]
    output = next(d for d in documents if d["kind"] == "output")
    assert set(output) == {"job_id", "sequence", "kind", "ends_job", "recorded_at", "output"}


def test_a_the_fixtures_are_what_real_jobs_emit_today() -> None:
    """R-015: regenerated by three real jobs, the fixtures are equal with the members that
    differ between generations masked (timestamps, output digests and sizes)."""
    import sys

    sys.path.insert(0, str(REPO_ROOT / "scripts"))
    from t07_schema_fixtures import EVENT_FIXTURES, job_documents, stable

    emitted = job_documents()
    assert sorted(emitted) == sorted([*JOB_FIXTURES.values(), *EVENT_FIXTURES])
    for name, document in emitted.items():
        assert stable(document) == stable(load_json(FIXTURES / name)), name


# ----------------------------------------------------------------------------------- item (b)


def test_b_two_outputs_and_a_progress_before_the_ending_event_are_accepted_in_order() -> None:
    first = ref("solution_certificate", 1, name="solution-certificate.json")
    second = ref("run_manifest", 2, name="run-manifest.json")
    events = [
        event(0, "accepted"),
        event(1, "started"),
        event(2, "output", output=first),
        event(3, "progress", progress=progress(4, "verify")),
        event(4, "output", output=second),
        event(5, "ended", ending=COMPLETED, error=None),
    ]
    finished = job(
        status="completed",
        outputs=(first, second),
        progress=progress(4, "verify"),
        event_count=len(events),
        started_at=AT,
        ended_at=LATER,
        ending=COMPLETED,
    )
    assert check_lifecycle(finished, events) == []
    assert finished.outputs == (first, second)
    # J2: nothing is read from the ending event's payload, which carries no output member.
    assert "output" not in events[-1].as_document()
    assert "outputs" not in events[-1].as_document()
    # The order is held, not merely the set.
    swapped = dataclasses.replace(finished, outputs=(second, first))
    assert [found.rule for found in check_lifecycle(swapped, events)] == [5]


# ----------------------------------------------------------------------------------- item (c)


def test_c_each_operation_has_exactly_one_request_branch() -> None:
    """A static walk: the enum values and the `oneOf` branch constants are the same, once each."""
    defs = _job_request_schema()
    enum = defs["operation"]["enum"]
    request = defs["job_request"]
    assert request["properties"]["operation"] == {"$ref": "#/$defs/operation"}
    constants = [branch["properties"]["operation"]["const"] for branch in request["oneOf"]]
    assert sorted(constants) == sorted(enum)
    assert len(constants) == len(set(constants))
    assert list(JOB_OPERATIONS) == enum == list(get_args(JobOperation))
    # Each branch selects its own body schema.
    bodies = {
        branch["properties"]["operation"]["const"]: branch["properties"]["body"]["$ref"]
        for branch in request["oneOf"]
    }
    assert bodies == {"solve": "#/$defs/solve_body", "reproduce": "#/$defs/reproduce_body"}


@pytest.mark.parametrize("operation", ["solve_resume", "optimize", "SOLVE", ""])
def test_c_an_operation_outside_the_enum_is_refused(operation: str) -> None:
    document = {"operation": operation, "idempotency_key": "k", "body": {"revision_id": "r"}}
    assert schema_errors(JOB_REQUEST, document) != []
    with pytest.raises(DocumentSchemaError):
        JobRequest.from_document(document)
    with pytest.raises(ValueError, match="is not one of"):
        JobRequest(operation, "k", SolveBody("r"))  # type: ignore[arg-type]


def test_c_a_solve_body_under_reproduce_is_refused() -> None:
    document = {"operation": "reproduce", "idempotency_key": "k", "body": {"revision_id": "r"}}
    assert schema_errors(JOB_REQUEST, document) != []
    with pytest.raises(DocumentSchemaError):
        JobRequest.from_document(document)
    with pytest.raises(ValueError, match="takes a ReproduceBody"):
        JobRequest("reproduce", "k", SolveBody("r"))


def test_c_a_reproduce_body_under_solve_is_refused() -> None:
    document = {
        "operation": "solve",
        "idempotency_key": "k",
        "body": {"bundle_artifact_id": "import-000001:bundle"},
    }
    assert schema_errors(JOB_REQUEST, document) != []
    with pytest.raises(ValueError, match="takes a SolveBody"):
        JobRequest("solve", "k", ReproduceBody("import-000001:bundle"))


def test_c_the_operation_is_required() -> None:
    document = {"idempotency_key": "k", "body": {"revision_id": "r"}}
    assert schema_errors(JOB_REQUEST, document) != []


# ----------------------------------------------------------------------------------- item (d)


def _newer_producer_solve() -> tuple[Job, list[JobEvent]]:
    """A finished solve as a newer producer writes it: an output of a kind this code does not
    know (`trajectory`), an event of an unknown kind mid-stream, and an unknown-kind event that
    ends the job — seen to end it only through `ends_job` (J5)."""
    finished, known = completed_solve()
    trajectory = ref("trajectory", 7, name="trajectory.json")
    outputs = (finished.outputs[0], trajectory, *finished.outputs[1:])
    stream: list[JobEvent] = [*known[:8]]  # accepted, started, six progress events
    for output in outputs:
        stream.append(event(len(stream), "output", output=output))
        if output is trajectory:
            stream.append(opaque(len(stream), "simulated_time_progress", ends_job=False, t=3.5))
    stream.append(opaque(len(stream), "ended_v2", ends_job=True, verdict="done"))
    newer = dataclasses.replace(finished, outputs=outputs, event_count=len(stream))
    assert check_lifecycle(newer, stream) == []
    return newer, stream


def _store_as_written(directory: Path, job: Job, events: list[JobEvent]) -> None:
    """The rows a newer producer leaves: the `kind` columns have no CHECK (§5.6)."""
    from openflowsheet.application.local import LocalApplication
    from openflowsheet.canonical import canonical_json

    document = job.as_document()
    with LocalApplication.open(directory) as application:
        store = application.store
        with store.writing() as connection:
            connection.execute(
                "INSERT INTO jobs (ordinal, job_id, operation, request, request_sha256,"
                " principal_id, capability_id, policy_sha256, status, owner_instance, outputs,"
                " progress, effective_budgets, cancel_requested, created_at, started_at,"
                " ended_at, ending, error) VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?, 'newer-producer',"
                " ?, ?, ?, 0, ?, ?, ?, ?, NULL)",
                (
                    job.job_id,
                    job.operation,
                    canonical_json(document["request"]),
                    job.request_sha256,
                    job.principal_id,
                    job.capability_id,
                    job.policy_sha256,
                    job.status,
                    canonical_json(document["outputs"]),
                    canonical_json(document["progress"]),
                    canonical_json(document["effective_budgets"]),
                    job.created_at,
                    job.started_at,
                    job.ended_at,
                    canonical_json(document["ending"]),
                ),
            )
            connection.executemany(
                "INSERT INTO events (job_id, sequence, kind, ends_job, document)"
                " VALUES (?, ?, ?, ?, ?)",
                [
                    (e.job_id, e.sequence, e.kind, int(e.ends_job), canonical_json(e.as_document()))
                    for e in events
                ],
            )


def test_d_the_cli_ignores_an_unknown_output_and_event_and_sees_the_job_end(
    tmp_path: Path,
) -> None:
    """ADR 0008 A1 (d), the CLI consumer (`openflowsheet api`): every job read exits 0; the
    unknown output stays in `outputs` and in the solve's result, the unknown events pass opaque
    with their payloads untouched, and the job's end is the event whose `ends_job` is true —
    an `ended_v2` this code has never heard of."""
    import json

    from t07_corpus import CORPUS
    from t07_jobs_support import commit
    from test_t07_w5b_cli import run_cli

    from openflowsheet.application.local import LocalApplication

    directory = tmp_path / "project"
    with LocalApplication.create(directory, project_id="adr0008-d") as application:
        # The newer job's request names `rev-1`; its result is re-derived from that revision.
        commit(application, CORPUS["SYN-001-nominal"](), "rev-1")
    newer, events = _newer_producer_solve()
    _store_as_written(directory, newer, events)

    def api(name: str, request: dict[str, Any]) -> Any:
        code, out, err = run_cli(
            ["api", name, "--project", str(directory), "--json", json.dumps(request)]
        )
        assert (code, err) == (0, ""), (name, out, err)
        return json.loads(out)

    shown = api("get_job", {"job_id": JOB_ID})
    assert shown["outputs"] == [output.as_document() for output in newer.outputs]
    assert shown["outputs"][1]["kind"] == "trajectory"

    page = api("list_job_events", {"job_id": JOB_ID})
    assert page["items"] == [item.as_document() for item in events]
    read = [JobEvent.from_document(item, lenient=True) for item in page["items"]]
    assert [item.kind for item in read if not item.known] == ["simulated_time_progress", "ended_v2"]
    assert [item.payload for item in read if not item.known] == [{"t": 3.5}, {"verdict": "done"}]
    # J5: the end is read from `ends_job`, never from `kind`.
    assert [item.kind for item in read if item.ends_job] == ["ended_v2"]
    assert check_lifecycle(Job.from_document(shown, lenient=True), read) == []

    waited = api("wait_job", {"job_id": JOB_ID, "after_sequence": len(events) - 2, "timeout_s": 0})
    assert waited["ended"] is True
    assert waited["events"] == [events[-1].as_document()]

    result = api("get_job_result", {"job_id": JOB_ID})
    assert result["run_result"]["job_status"] == "completed"
    assert result["run_result"]["outputs"] == shown["outputs"]
