"""SYN-001 oracle compared against Fable's independent 20-digit reference values.

Implements items A.4, the reference half of C, D, E and L of
`docs/derivations/SYN-001-oracle-spec.md` §4.

`benchmarks/syn001/reference_values.yaml` was generated by Fable with mpmath at 40 significant
digits from the plan §3.1 definitions only, by
`docs/derivations/scripts/syn001_reference.py`. It is independent of the oracle implementation
and is never regenerated from it: that would turn an independent expectation into a
self-generated regression fixture (CLAUDE.md, "Scientific conduct"). This file only reads it. A
disagreement is reported as a failure, not accommodated by loosening a tolerance.

Comparison tolerance, from the specification: relative 1e-13 or absolute 1e-14, whichever is
looser, unless a tighter or looser one is stated for a particular quantity.
"""

from __future__ import annotations

import math
import re
from pathlib import Path
from typing import Any

import pytest
from conftest import load_json, sha256_of

from benchmarks.syn001.oracle import SYN001, k_values, recycle_oracle

FRESH_FEED = (1.0, 1.0, 1.0)
COMPONENTS = (0, 1, 2)

REFERENCE_RELATIVE = 1e-13
REFERENCE_ABSOLUTE = 1e-14

# A template placeholder: an angle bracket immediately followed by a non-space character, as in
# `<actual commit hash>`. Prose such as "r < 1 ... as r -> 1" is not a placeholder, so the
# opening bracket must not be followed by whitespace.
ANGLE_PLACEHOLDER = re.compile(r"<[^<>\s][^<>]*>")
K_GRID_KEY = re.compile(r"^T=(?P<T>[0-9.]+)K,P=(?P<P>[0-9.]+)Pa$")

VARIANT_INPUTS: dict[str, tuple[float, float]] = {
    "SYN-001-nominal": (0.5, 360.0),
    "SYN-001-once-through": (0.0, 360.0),
    "SYN-001-high-recycle": (0.95, 360.0),
    "SYN-001-all-liquid-310K": (0.5, 310.0),
    "SYN-001-all-vapor-420K": (0.5, 420.0),
}

VARIANT_IDS = tuple(VARIANT_INPUTS)


def close(actual: float, expected_text: str | float, *, rel: float = REFERENCE_RELATIVE) -> None:
    """Assert `actual` matches the reference, at `rel` relative or 1e-14 absolute, whichever is
    looser. The reference is parsed from its decimal string; no rounding of the reference."""
    expected = float(expected_text)
    tolerance = max(REFERENCE_ABSOLUTE, rel * abs(expected))
    assert abs(actual - expected) <= tolerance, (
        f"got {actual!r}, reference {expected_text!r}, "
        f"deviation {abs(actual - expected):.3e} > tolerance {tolerance:.3e}"
    )


def variant(reference_values: dict[str, Any], case_id: str) -> dict[str, Any]:
    for entry in reference_values["variants"]:
        if entry["case_id"] == case_id:
            assert isinstance(entry, dict)
            return entry
    raise AssertionError(f"{case_id} is not present in reference_values.yaml")


def result_for(case_id: str) -> Any:
    r, T_flash = VARIANT_INPUTS[case_id]
    return recycle_oracle(FRESH_FEED, r, T_flash, case_id=case_id)


def is_undefined(reference_field: Any) -> bool:
    """The reference file writes `undefined ...` where a composition or ratio does not exist."""
    return isinstance(reference_field, str) and reference_field.startswith("undefined")


# --------------------------------------------------------------------------------------------
# A.4 K-values on the reference grid
# --------------------------------------------------------------------------------------------


def test_a4_k_values_match_the_reference_grid(reference_values: dict[str, Any]) -> None:
    """Every `K_values` entry of the reference file (specification §4 A.4)."""
    grid = reference_values["K_values"]
    assert isinstance(grid, dict) and grid, "the reference file has no K_values table"
    for key, expected in grid.items():
        match = K_GRID_KEY.match(key)
        assert match is not None, f"unparsable K_values key {key!r}"
        actual = k_values(float(match.group("T")), float(match.group("P")))
        for index in COMPONENTS:
            close(actual[index], expected[index])


def test_a4_reference_constants_match_the_oracle_constants(
    reference_values: dict[str, Any],
) -> None:
    """The oracle's `Syn001Constants` are the constants the reference was generated from."""
    constants = reference_values["constants"]
    close(SYN001.R, constants["R"])
    close(SYN001.T_r, constants["T_r_K"])
    close(SYN001.P_r, constants["P_r_Pa"])
    for index in COMPONENTS:
        close(SYN001.c_p[index], constants["c_p_J_per_mol_K"])
        close(SYN001.T_b[index], constants["T_b_K"][index])
        close(SYN001.L[index], constants["L_J_per_mol"][index])
        close(SYN001.v[index], constants["v_m3_per_mol"][index])
        close(SYN001.M[index], constants["M_kg_per_mol"][index])


def test_a3_pure_component_checks_match_the_reference(reference_values: dict[str, Any]) -> None:
    """K_i(T_b,i, P_r) = 1 and h_i^V - h_i^L = L_i, against the reference file's own values."""
    checks = reference_values["pure_component_checks"]
    for index, name in enumerate(("A", "B", "C")):
        close(k_values(SYN001.T_b[index], SYN001.P_r)[index], checks[f"K_{name}(T_b,P_r)"])
        close(SYN001.L[index], checks[f"h_vap_{name}_at_P_r_J_per_mol"])


def test_a4_fresh_feed_summary_values_match_the_reference(
    reference_values: dict[str, Any],
) -> None:
    """`sum z K` at 350 K and 310 K, and `sum z/K` at 420 K, for the equimolar feed."""
    feed = reference_values["fresh_feed"]
    z = 1.0 / 3.0
    close(math.fsum(z * k for k in k_values(350.0, SYN001.P_r)), feed["sum_zK_at_350K"])
    close(math.fsum(z * k for k in k_values(310.0, SYN001.P_r)), feed["sum_zK_at_310K"])
    close(math.fsum(z / k for k in k_values(420.0, SYN001.P_r)), feed["sum_z_over_K_at_420K"])


# --------------------------------------------------------------------------------------------
# C. Flash results against the reference, for the fresh feed and each mixed feed
# --------------------------------------------------------------------------------------------


@pytest.mark.parametrize("case_id", VARIANT_IDS)
def test_c_fresh_feed_flash_matches_the_reference(
    case_id: str, reference_values: dict[str, Any]
) -> None:
    """The fresh-feed flash at (T_flash, P_r): state, beta, x, y, V, K (specification §4 C)."""
    expected = variant(reference_values, case_id)
    flash = result_for(case_id).flash
    assert flash.state == expected["flash_phase_state"]
    close(flash.beta, expected["beta_fresh_feed_vapor_fraction"])
    close(flash.V, expected["V_mol_per_s"])
    close(flash.sum_zK, expected["sum_zK_fresh"])
    close(flash.sum_z_over_K, expected["sum_z_over_K_fresh"])
    for index in COMPONENTS:
        close(flash.K[index], expected["K_at_flash"][index])
    if is_undefined(expected["x"]):
        assert flash.x is None
    else:
        assert flash.x is not None
        for index in COMPONENTS:
            close(flash.x[index], expected["x"][index])
        assert math.fsum(flash.x) == pytest.approx(1.0, abs=1e-14)
    if is_undefined(expected["y"]):
        assert flash.y is None
    else:
        assert flash.y is not None
        for index in COMPONENTS:
            close(flash.y[index], expected["y"][index])
        assert math.fsum(flash.y) == pytest.approx(1.0, abs=1e-14)
    assert abs(flash.rr_residual) <= 1e-14


@pytest.mark.parametrize("case_id", VARIANT_IDS)
def test_c_heater_outlet_flash_matches_the_reference(
    case_id: str, reference_values: dict[str, Any]
) -> None:
    """The mixed feed flashed at (350 K, P_r): the heater's TP-state outlet (§4 C, E)."""
    expected = variant(reference_values, case_id)
    heater = result_for(case_id).heater_outlet
    assert heater.state == expected["heater_outlet_state"]
    close(heater.beta, expected["heater_outlet_vapor_fraction"])
    close(heater.sum_zK, expected["sum_zK_at_350K_mixed"])
    close(heater.sum_z_over_K, expected["sum_z_over_K_at_350K_mixed"])
    assert heater.x is not None
    for index in COMPONENTS:
        close(heater.x[index], expected["heater_outlet_x"][index])
    if is_undefined(expected["heater_outlet_y"]):
        assert heater.y is None
    else:
        assert heater.y is not None
        for index in COMPONENTS:
            close(heater.y[index], expected["heater_outlet_y"][index])


# --------------------------------------------------------------------------------------------
# D. The nominal case in full
# --------------------------------------------------------------------------------------------

PLAN_NOMINAL = {
    "q": 0.4150855900,
    "L": 3.2783818616,
    "V": 1.3608090692,
    "x": (0.1816607866, 0.3333333333, 0.4850058800),
}


def test_d_nominal_matches_the_plan_printed_digits() -> None:
    """q, L, V and x against the digits printed in implementation plan §3.2 (§4 D)."""
    result = result_for("SYN-001-nominal")
    assert result.q is not None
    liquid = math.fsum(result.recycle) + math.fsum(result.purge)
    assert result.q == pytest.approx(PLAN_NOMINAL["q"], abs=1e-10)
    assert liquid == pytest.approx(PLAN_NOMINAL["L"], abs=1e-10)
    assert result.flash.V == pytest.approx(PLAN_NOMINAL["V"], abs=1e-10)
    assert result.flash.x is not None
    for index in COMPONENTS:
        assert result.flash.x[index] == pytest.approx(PLAN_NOMINAL["x"][index], abs=1e-10)


def test_d_nominal_residuals_are_far_inside_the_registered_tolerances() -> None:
    """balance_residual <= 1e-14 mol/s and energy_residual <= 1e-9 W (specification §4 D)."""
    result = result_for("SYN-001-nominal")
    assert max(abs(value) for value in result.balance_residual) <= 1e-14
    assert abs(result.energy_residual) <= 1e-9


# --------------------------------------------------------------------------------------------
# E. Every registered variant, every numeric field and every phase state
# --------------------------------------------------------------------------------------------


@pytest.mark.parametrize("case_id", VARIANT_IDS)
def test_e_variant_phase_states_match_the_reference(
    case_id: str, reference_values: dict[str, Any]
) -> None:
    """All six recorded phase signatures match exactly (specification §4 E)."""
    expected = variant(reference_values, case_id)
    result = result_for(case_id)
    assert result.flash.state == expected["flash_phase_state"]
    assert result.recycle_state == expected["recycle_phase_signature"]
    assert result.vapor_product_state == expected["vapor_product_phase_signature"]
    assert result.purge_state == expected["purge_phase_signature"]
    assert result.mixer_outlet_state == expected["mixer_outlet_state"]
    assert result.heater_outlet.state == expected["heater_outlet_state"]


@pytest.mark.parametrize("case_id", VARIANT_IDS)
def test_e_variant_stream_flows_match_the_reference(
    case_id: str, reference_values: dict[str, Any]
) -> None:
    """Vapor product, purge, recycle and mixed feed, component by component (§4 E)."""
    expected = variant(reference_values, case_id)
    result = result_for(case_id)
    for index in COMPONENTS:
        close(result.vapor_product[index], expected["vapor_product_mol_per_s"][index])
        close(result.purge[index], expected["purge_mol_per_s"][index])
        close(result.recycle[index], expected["recycle_mol_per_s"][index])
        close(result.mixed_feed[index], expected["mixed_feed_mol_per_s"][index])
    liquid = math.fsum(result.recycle) + math.fsum(result.purge)
    close(liquid, expected["L_mol_per_s"])
    if is_undefined(expected["q_V_over_L"]):
        assert result.q is None
    else:
        assert result.q is not None
        close(result.q, expected["q_V_over_L"])


@pytest.mark.parametrize("case_id", VARIANT_IDS)
def test_e_zero_flow_streams_are_exactly_zero(
    case_id: str, reference_values: dict[str, Any]
) -> None:
    """A dormant stream is exactly 0.0 in every component, not merely small (ADR 0001 D3.1)."""
    expected = variant(reference_values, case_id)
    result = result_for(case_id)
    dormant = {
        "recycle_phase_signature": result.recycle,
        "purge_phase_signature": result.purge,
        "vapor_product_phase_signature": result.vapor_product,
    }
    checked = 0
    for key, stream in dormant.items():
        if expected[key] != "ZERO_FLOW":
            continue
        for index in COMPONENTS:
            assert stream[index] == 0.0, f"{key} component {index} is {stream[index]!r}"
            assert math.copysign(1.0, stream[index]) > 0.0, "signed zero was not normalized"
        checked += 1
    if case_id in ("SYN-001-once-through", "SYN-001-all-liquid-310K"):
        assert checked == 1
    elif case_id == "SYN-001-all-vapor-420K":
        assert checked == 2


@pytest.mark.parametrize("case_id", VARIANT_IDS)
def test_e_variant_temperatures_and_duties_match_the_reference(
    case_id: str, reference_values: dict[str, Any]
) -> None:
    """T_mix, the mixer subcooling margin, and both duties (specification §4 E)."""
    expected = variant(reference_values, case_id)
    result = result_for(case_id)
    close(result.T_mix, expected["T_mix_K"])
    close(result.sum_zK_at_T_mix, expected["sum_zK_at_T_mix"])
    close(result.Q_heater, expected["Q_heater_W"])
    close(result.Q_flash, expected["Q_flash_W"])
    close(result.Q_heater + result.Q_flash, expected["Q_total_W"])


@pytest.mark.parametrize("case_id", VARIANT_IDS)
def test_e_variant_enthalpy_flows_match_the_reference(
    case_id: str, reference_values: dict[str, Any]
) -> None:
    """Every H_* field of the reference table (specification §4 E)."""
    expected = variant(reference_values, case_id)
    result = result_for(case_id)
    close(result.H_fresh, expected["H_fresh_W"])
    close(result.H_recycle, expected["H_recycle_W"])
    close(result.H_mixed, expected["H_mixed_W"])
    close(result.H_heater_out, expected["H_heater_out_W"])
    close(result.H_flash_out, expected["H_flash_out_W"])
    close(
        result.H_products - result.H_fresh,
        expected["H_products_minus_H_fresh_W"],
    )


def test_e_high_recycle_heater_duty_is_negative() -> None:
    """ADR 0001 D4.2: the r = 0.95 heater cools. An implementation asserting Q >= 0 fails."""
    assert result_for("SYN-001-high-recycle").Q_heater < 0.0


def test_e_linear_recycle_matches_the_reference(reference_values: dict[str, Any]) -> None:
    """The analytic linear recycle values recorded in the reference file (§4 I)."""
    from benchmarks.syn001.oracle import linear_recycle

    entry = reference_values["linear_recycle"]
    f = tuple(float(value) for value in entry["f"])
    for key, expected in entry["values"].items():
        r = float(key.split("=")[1])
        for value in linear_recycle(f, r):
            close(value, expected)


# --------------------------------------------------------------------------------------------
# L. Reference file integrity
# --------------------------------------------------------------------------------------------


def _strings(node: Any, path: str = "$") -> list[tuple[str, str]]:
    if isinstance(node, str):
        return [(path, node)]
    if isinstance(node, dict):
        found: list[tuple[str, str]] = []
        for key, value in node.items():
            found.extend(_strings(key, f"{path}.<key>"))
            found.extend(_strings(value, f"{path}.{key}"))
        return found
    if isinstance(node, list):
        return [
            item for index, value in enumerate(node) for item in _strings(value, f"{path}[{index}]")
        ]
    return []


def test_l_reference_file_parses_and_has_no_angle_bracket_placeholders(
    reference_values: dict[str, Any],
) -> None:
    """The file parses, and no value is a template placeholder (specification §4 L)."""
    assert reference_values["variants"], "the reference file registers no variants"
    offenders = [
        f"{path}: {text}"
        for path, text in _strings(reference_values)
        if ANGLE_PLACEHOLDER.search(text)
    ]
    assert not offenders, "angle-bracket placeholders are never valid values: " + "; ".join(
        offenders
    )


def test_l_every_reference_variant_is_registered(
    reference_values: dict[str, Any], registry: dict[str, Any]
) -> None:
    """Every variant in the reference file appears in benchmarks/registry.yaml (§4 L)."""
    registered = {case["case_id"] for case in registry["cases"]}
    for entry in reference_values["variants"]:
        assert entry["case_id"] in registered, f"{entry['case_id']} is not registered"


def test_l_registry_records_the_reference_file_digest(repo_root: Path) -> None:
    """The registry pins the exact reference bytes it was registered against."""
    digest = sha256_of(repo_root / "benchmarks" / "syn001" / "reference_values.yaml")
    registry_text = (repo_root / "benchmarks" / "registry.yaml").read_text(encoding="utf-8")
    assert digest in registry_text, (
        f"benchmarks/registry.yaml does not record the current reference digest {digest}; "
        "either the reference file changed deliberately, in which case update the registry, "
        "or it changed by accident"
    )


def test_l_reference_digest_is_recorded_in_the_p01_evidence_manifest(repo_root: Path) -> None:
    """Specification §4 L: the sha256 of the reference file is recorded in the P01 manifest.

    Fable writes `evidence/P01/<commit>/manifest.json`; Opus must not write an evidence
    manifest for a package it does not lead. Until it exists this test skips with the reason,
    and it fails if a manifest exists without the digest.
    """
    manifests = sorted((repo_root / "evidence" / "P01").glob("*/manifest.json"))
    if not manifests:
        pytest.skip(
            "no evidence/P01/<commit>/manifest.json yet; Fable 5.1 leads P01 and writes it "
            "after verification (CLAUDE.md, 'Branch and merge discipline')"
        )
    digest = sha256_of(repo_root / "benchmarks" / "syn001" / "reference_values.yaml")
    for manifest_path in manifests:
        blob = load_json(manifest_path)
        assert digest in repr(blob), (
            f"{manifest_path} does not record the reference file digest {digest}"
        )
