"""T08.A00/A01: the T08 reference generators re-derive every claim (T08 release spec §9, §10).

``docs/derivations/scripts/t08_reference.py --check`` re-derives the release specification's claims
(the fourteen cited manifests of §3.1 among them, T08.A01; the assertion catalogue against the
specification's own table, T08.A00) and requires the committed YAML to equal the regenerated bytes.
``t08_build_first_reference.py --check`` does the same for the build-first specification. Both run
in seconds, so they run on every gate. The claim counts are the generators' own; a generator that
silently drops a claim still has to say "N of N" with every claim passing.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "docs" / "derivations" / "scripts"

_PASS = re.compile(r"^(\d+) of (\d+) claims pass$", re.MULTILINE)
_BYTES = re.compile(
    r"^committed YAML equals the regenerated bytes \(sha256 [0-9a-f]{64}\)$", re.MULTILINE
)


@pytest.mark.parametrize("generator", ["t08_reference.py", "t08_build_first_reference.py"])
def test_a00_generator_check_passes(generator: str) -> None:
    completed = subprocess.run(
        [sys.executable, str(SCRIPTS / generator), "--check"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=600,
        check=False,
    )
    output = completed.stdout + completed.stderr
    assert completed.returncode == 0, output
    passed = _PASS.search(completed.stdout)
    assert passed is not None, output
    assert passed.group(1) == passed.group(2), output
    assert int(passed.group(2)) > 0, output
    assert _BYTES.search(completed.stdout) is not None, output
