"""K01: the CompiledProblem schemas, their round-trip fixtures, and the rules they cannot state.

Plan §2.2 assigns "CompiledProblem metadata, EvaluationResult, Jacobian metadata" to the P02/K01
row, and ADR 0008 D4.1 names the promotion of these schemas to `schemas/` as the window in which
`parameter_ids` and `row_accumulation` are added. This module exercises all three.

**The valid fixtures are real output.** They are generated by compiling SYN-001 and serializing what
the boundary actually returned, following the P01 precedent that the documents the package uses are
the documents the schema is exercised against, so the two cannot drift apart. S1 is on-solution, S5
is off-solution with every row and entry generic, and the out-of-domain pair is the honest
"no values, no entries" shape — a document class a schema alone would happily confuse with success.

**Every invalid fixture is wrong in exactly one way** and carries a `_why_invalid` line saying so.
Half of them are rejected by the schema and half only by `openflowsheet.serialize`'s cross-field
checks, and the test asserts that *each* is rejected by *something* — a fixture nothing rejects is a
hole, and would silently become a passing test if left as one.

`PropertyCapabilities` is on the same plan row and is deliberately **not** promoted here. No
`PropertyProvider` exists yet; the plan says to add a schema when the object it describes is used
and not in advance, so it waits for K02.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest
from conftest import load_json
from jsonschema import Draft202012Validator

from openflowsheet.serialize import (
    DocumentError,
    check_evaluation_document,
    check_jacobian_document,
    check_metadata_document,
    check_pairing,
    evaluation_result_from_document,
    evaluation_result_to_document,
    jacobian_result_from_document,
    jacobian_result_to_document,
    metadata_from_document,
    metadata_to_document,
)

#: fixture directory -> (schema file, cross-field checker)
KINDS: dict[str, tuple[str, Any]] = {
    "compiled_problem_metadata": ("compiled-problem-metadata.schema.json", check_metadata_document),
    "evaluation_result": ("evaluation-result.schema.json", check_evaluation_document),
    "jacobian_result": ("jacobian-result.schema.json", check_jacobian_document),
}

ROUND_TRIPS = {
    "compiled_problem_metadata": (metadata_from_document, metadata_to_document),
    "evaluation_result": (evaluation_result_from_document, evaluation_result_to_document),
    "jacobian_result": (jacobian_result_from_document, jacobian_result_to_document),
}


def fixtures(repo_root: Path, kind: str, validity: str) -> list[Path]:
    return sorted((repo_root / "tests" / "fixtures" / "schemas" / kind / validity).glob("*.json"))


def all_fixtures(validity: str) -> list[tuple[str, Path]]:
    root = Path(__file__).resolve().parent.parent
    return [(kind, path) for kind in KINDS for path in fixtures(root, kind, validity)]


def validator(repo_root: Path, kind: str) -> Draft202012Validator:
    schema = load_json(repo_root / "schemas" / KINDS[kind][0])
    return Draft202012Validator(schema)


def without_annotation(document: dict[str, Any]) -> dict[str, Any]:
    """Strip the `_why_invalid` line the invalid fixtures carry to document their intent."""
    return {key: value for key, value in document.items() if key != "_why_invalid"}


@pytest.mark.parametrize("kind", sorted(KINDS))
def test_the_schema_is_itself_valid(repo_root: Path, kind: str) -> None:
    Draft202012Validator.check_schema(load_json(repo_root / "schemas" / KINDS[kind][0]))


@pytest.mark.parametrize(
    ("kind", "path"), all_fixtures("valid"), ids=lambda value: getattr(value, "stem", value)
)
def test_a_valid_fixture_validates_and_passes_the_cross_field_rules(
    repo_root: Path, kind: str, path: Path
) -> None:
    document = load_json(path)
    problems = sorted(validator(repo_root, kind).iter_errors(document), key=lambda e: list(e.path))
    assert not problems, f"{path}: " + "; ".join(f"{list(e.path)}: {e.message}" for e in problems)
    KINDS[kind][1](document)


@pytest.mark.parametrize(
    ("kind", "path"), all_fixtures("valid"), ids=lambda value: getattr(value, "stem", value)
)
def test_a_valid_fixture_round_trips_through_json_and_through_the_dataclass(
    repo_root: Path, kind: str, path: Path
) -> None:
    """Two round trips: JSON text, and the typed object. Neither may lose or invent a field."""
    document = load_json(path)

    reloaded = json.loads(json.dumps(document, allow_nan=False, sort_keys=True))
    assert reloaded == document, f"{path} did not survive the JSON round trip"

    decode, encode = ROUND_TRIPS[kind]
    reencoded = encode(decode(document))
    assert reencoded == document, (
        f"{path} did not survive the dataclass round trip; the serializer and the schema disagree "
        "about some field"
    )
    assert not list(validator(repo_root, kind).iter_errors(reencoded))


@pytest.mark.parametrize(
    ("kind", "path"), all_fixtures("invalid"), ids=lambda value: getattr(value, "stem", value)
)
def test_an_invalid_fixture_is_rejected_by_the_schema_or_the_cross_field_rules(
    repo_root: Path, kind: str, path: Path
) -> None:
    """Each is wrong in exactly one way; something must catch it. A hole would pass silently."""
    raw = load_json(path)
    assert "_why_invalid" in raw, f"{path} does not say what is wrong with it"
    document = without_annotation(raw)

    schema_rejected = bool(list(validator(repo_root, kind).iter_errors(document)))
    try:
        KINDS[kind][1](document)
        checker_rejected = False
    except (DocumentError, KeyError, TypeError, IndexError):
        checker_rejected = True

    assert schema_rejected or checker_rejected, (
        f"{path} is accepted by both the schema and the cross-field checks, but it is listed as "
        f"invalid because: {raw['_why_invalid']}"
    )


def test_the_residual_and_jacobian_fixtures_of_one_state_pair(repo_root: Path) -> None:
    """ADR 0008 D2.4 across two serialized documents, which is where pairing usually breaks."""
    for state in ("s1", "s5", "out_of_domain"):
        evaluation = load_json(
            repo_root / "tests/fixtures/schemas/evaluation_result/valid" / f"syn001_{state}.json"
        )
        jacobian = load_json(
            repo_root / "tests/fixtures/schemas/jacobian_result/valid" / f"syn001_{state}.json"
        )
        check_pairing(evaluation, jacobian)


def test_documents_from_different_states_are_reported_as_not_pairing(repo_root: Path) -> None:
    """Anti-vacuity: the pairing check above must be capable of failing."""
    first = load_json(repo_root / "tests/fixtures/schemas/evaluation_result/valid/syn001_s1.json")
    other = load_json(repo_root / "tests/fixtures/schemas/jacobian_result/valid/syn001_s5.json")
    with pytest.raises(DocumentError, match="differs between"):
        check_pairing(first, other)


def test_the_metadata_fixture_is_the_syn001_problem(repo_root: Path) -> None:
    """The fixture is real output, so it must still describe the problem it claims to."""
    metadata = metadata_from_document(
        load_json(
            repo_root / "tests/fixtures/schemas/compiled_problem_metadata/valid/syn001_lifted.json"
        )
    )
    assert metadata.backend == "casadi"
    assert len(metadata.variable_ids) == len(metadata.equation_ids) == 17
    assert set(metadata.row_accumulation) == set(metadata.equation_ids)
    assert metadata.capabilities.hessian == "absent"
    assert metadata.parameter_ids == (
        "feed_A",
        "feed_B",
        "feed_C",
        "h_feed",
        "t_spec",
        "p_spec",
    )


def test_the_jacobian_fixture_carries_the_registered_pattern(repo_root: Path) -> None:
    result = jacobian_result_from_document(
        load_json(repo_root / "tests/fixtures/schemas/jacobian_result/valid/syn001_s5.json")
    )
    assert result.nnz == 60
    assert (len(result.row_ids), len(result.col_ids)) == (17, 17)
    assert result.pattern_provenance == "backend-declared"


def test_an_out_of_domain_document_reports_absence_rather_than_zeros(repo_root: Path) -> None:
    """The document class a schema alone would confuse with success."""
    evaluation = load_json(
        repo_root / "tests/fixtures/schemas/evaluation_result/valid/syn001_out_of_domain.json"
    )
    jacobian = load_json(
        repo_root / "tests/fixtures/schemas/jacobian_result/valid/syn001_out_of_domain.json"
    )
    assert evaluation["status"] == jacobian["status"] == "invalid_trial_state"
    assert evaluation["values"] is None
    assert jacobian["data"] == [] and jacobian["nnz"] == 0
    assert "outside" in evaluation["message"]


def test_the_schemas_readme_lists_what_k01_promoted(repo_root: Path) -> None:
    """The index that tells a reader which schemas exist must not go stale."""
    readme = (repo_root / "schemas" / "README.md").read_text(encoding="utf-8")
    for name, _ in KINDS.values():
        assert name in readme, f"schemas/README.md does not mention {name}"
