"""K01 acceptance: SYN-001 compiled by the production compiler, against 20-digit references.

Plan §4.2 names K01's acceptance as "expression/callback conformance fixtures, dimensions and
sparsity, original-equation reconstruction". This is that, on the lifted 17x17 form P02 matched
across both backends.

**What the expectation is, and why it is independent.** `benchmarks/p02/reference_values.yaml` was
generated by Fable with mpmath at 40 digits from the SYN-001 derivation's closed forms, with no
backend and no oracle import. The compiler assembles 17 rows from separate declarations and obtains
every Jacobian entry by algorithmic differentiation through an opaque callback's declared-sparse
chain rule; the reference evaluated whole residuals and differentiated by hand. The composition and
the derivatives are therefore genuinely independent of the thing they are compared against, which
is what makes this verification rather than a regression fixture.

The block *values* are not independent: `benchmarks/k01/syn001.py` imports the same closed forms
`benchmarks/p02/expected.py` provides. That is stated rather than hidden, and it is why the
assertions that carry weight here are the assembled ones.

**The tolerance is the registered one**, reused verbatim from `benchmarks/p02/judge.py` rather than
invented: `1e-13 * (|expected| + scale)`, where the scale is the row scale for a residual and the
row/column scale ratio for a Jacobian entry. The floor matters. Four of the six registered states
sit on the solution, so their reference residuals are round-off — 1e-17 and smaller. Comparing
those *relatively* would demand that two correct implementations agree on noise, and would report a
100% deviation between two answers that are both exactly right.
"""

from __future__ import annotations

import numpy as np
import pytest

from benchmarks.k01.syn001 import LABEL_L, PARAMETER_IDS, HBlock, KBlock, syn001_spec
from benchmarks.p02 import expected as closed_form
from benchmarks.p02.reference import ReferenceState, load_reference
from openflowsheet.canonical import split_model_version, structure_sha256
from openflowsheet.compile.casadi_backend import compile_problem
from openflowsheet.compiled import EvaluationContext

TOLERANCE_FACTOR = 1e-13
REFERENCE = load_reference()
STATE_IDS = tuple(sorted(REFERENCE.states))

#: Both compiled forms are judged, and the second one is the point.
#:
#: In the **lifted** form each block output reaches the system exactly once, through its own
#: definitional row, with coefficient −1 — so the callback's chain rule is only ever exercised as a
#: ±1 pass-through and no test here composed a block output with a non-unit outer derivative. The
#: Fable review of K01 identified that as a gap between what this evidence showed and what it was
#: described as showing. In the **inlined** form the block outputs are substituted into the
#: equilibrium and energy rows, so `d(eq_i)/dT` carries `exp(lnK_i)·dlnK_i/dT·l_i·V` and the
#: declared-sparse callback derivative is genuinely composed. `reference_values.yaml` already
#: carried `residual_I`/`jacobian_I` at every state, so this cost no new reference work.
FORMS = ("L", "I")
CASES = tuple((state_id, form) for state_id in STATE_IDS for form in FORMS)


def scale_ratio(key: str) -> float:
    row, column = key.split("|")
    return closed_form.ROW_SCALES[row] / closed_form.COLUMN_SCALES[column]


def compiled_at(
    state: ReferenceState, form: str = "L"
) -> tuple[object, EvaluationContext, np.ndarray]:
    spec = syn001_spec(state.parameters, form=form)
    problem = compile_problem(spec)
    context = EvaluationContext(
        model_version=problem.metadata.model_version,
        constants_sha256=problem.metadata.constants_sha256,
    )
    values = state.x_i if form == "I" else state.x_l
    x = np.array([values[name] for name in spec.variable_ids], dtype=np.float64)
    return problem, context, x


def expected_residual(state: ReferenceState, form: str) -> dict[str, float]:
    return state.residual_i if form == "I" else state.residual_l


def expected_jacobian(state: ReferenceState, form: str) -> dict[str, float]:
    return state.jacobian_i if form == "I" else state.jacobian_l


def registered_equations(form: str) -> tuple[str, ...]:
    return closed_form.EQUATION_IDS_I if form == "I" else closed_form.EQUATION_IDS_L


def jacobian_entries(result: object) -> dict[str, float]:
    """Read a `JacobianResult` back into `{"row|col": value}` — by name, never by position."""
    entries: dict[str, float] = {}
    for column, col_id in enumerate(result.col_ids):  # type: ignore[attr-defined]
        for offset in range(result.indptr[column], result.indptr[column + 1]):  # type: ignore[attr-defined]
            entries[f"{result.row_ids[result.indices[offset]]}|{col_id}"] = result.data[offset]  # type: ignore[attr-defined]
    return entries


@pytest.mark.parametrize(("state_id", "form"), CASES)
def test_the_assembled_residual_matches_the_reference(state_id: str, form: str) -> None:
    state = REFERENCE.states[state_id]
    problem, context, x = compiled_at(state, form)
    result = problem.residual(x, context)  # type: ignore[attr-defined]

    assert result.status == "ok", result.message
    assert result.equation_ids == registered_equations(form)
    got = dict(zip(result.equation_ids, result.values, strict=True))
    assert set(got) == set(expected_residual(state, form))

    worst, where = 0.0, ""
    for key, value in expected_residual(state, form).items():
        tolerance = TOLERANCE_FACTOR * (abs(value) + closed_form.ROW_SCALES[key])
        deviation = abs(got[key] - value) / tolerance
        if deviation > worst:
            worst, where = deviation, key
    assert worst <= 1.0, f"{state_id} form {form}: worst residual dev {worst:.3g} at {where!r}"


@pytest.mark.parametrize(("state_id", "form"), CASES)
def test_the_assembled_jacobian_matches_the_reference(state_id: str, form: str) -> None:
    """The load-bearing assertion, and in form I the one that exercises the chain rule."""
    state = REFERENCE.states[state_id]
    problem, context, x = compiled_at(state, form)
    result = problem.jacobian(x, context)  # type: ignore[attr-defined]
    expected = expected_jacobian(state, form)

    assert result.status == "ok", result.message
    entries = jacobian_entries(result)
    assert set(entries) == set(expected), (
        f"{state_id} form {form}: assembled pattern differs from the reference. "
        f"Missing {sorted(set(expected) - set(entries))}; "
        f"unexpected {sorted(set(entries) - set(expected))}"
    )

    worst, where = 0.0, ""
    for key, value in expected.items():
        tolerance = TOLERANCE_FACTOR * (abs(value) + scale_ratio(key))
        deviation = abs(entries[key] - value) / tolerance
        if deviation > worst:
            worst, where = deviation, key
    assert worst <= 1.0, f"{state_id} form {form}: worst Jacobian dev {worst:.3g} at {where!r}"


@pytest.mark.parametrize(("state_id", "form"), CASES)
def test_the_assembled_pattern_is_the_registered_one(state_id: str, form: str) -> None:
    """17 x 17 with 60 structural nonzeros — the shape P02 matched across both backends.

    Six of those zeros exist only because `HBlock` declares that an enthalpy output does not depend
    on another component's liquid flow, and the compiler tells the backend that the declaration
    exists. Without that, the count is larger and every entry is still numerically right, which is
    exactly why the count is asserted and not merely observed.
    """
    state = REFERENCE.states[state_id]
    problem, context, x = compiled_at(state, form)
    result = problem.jacobian(x, context)  # type: ignore[attr-defined]

    size, nnz = (11, 43) if form == "I" else (17, 60)
    assert (len(result.row_ids), len(result.col_ids)) == (size, size)
    assert result.nnz == nnz
    expected_pattern = REFERENCE.pattern_i if form == "I" else REFERENCE.pattern_l
    assert tuple(sorted(jacobian_entries(result))) == expected_pattern
    assert result.pattern_provenance == "backend-declared"


@pytest.mark.parametrize(("state_id", "form"), CASES)
def test_each_block_is_called_once_per_evaluation(state_id: str, form: str) -> None:
    """ADR 0003 D5.5 on the real fixture. Block H has five inputs, so differencing would be six."""
    state = REFERENCE.states[state_id]
    problem, context, x = compiled_at(state, form)

    residual = problem.residual(x, context)  # type: ignore[attr-defined]
    for block_id in ("blockK", "blockH"):
        assert residual.counters[block_id] == {"value_calls": 1, "jacobian_calls": 0}

    jacobian = problem.jacobian(x, context)  # type: ignore[attr-defined]
    for block_id, n_inputs in (("blockK", 2), ("blockH", 5)):
        counts = jacobian.counters[block_id]
        assert counts["jacobian_calls"] == 1
        assert counts["value_calls"] <= 1 < n_inputs + 1, (
            f"{block_id}: {counts['value_calls']} value calls per Jacobian; "
            f"{n_inputs + 1} is the finite-difference signature"
        )


@pytest.mark.parametrize("state_id", STATE_IDS)
def test_reconstruct_returns_the_original_named_variables(state_id: str) -> None:
    """Plan §4.2's "original-equation reconstruction" at the variable level."""
    state = REFERENCE.states[state_id]
    problem, context, x = compiled_at(state)
    reconstructed = problem.reconstruct(x, context)  # type: ignore[attr-defined]
    assert reconstructed.variables == {name: state.x_l[name] for name in closed_form.VARIABLE_IDS_L}


def test_the_residual_and_jacobian_agree_on_identity_at_every_state() -> None:
    """`docs/interfaces-frozen.md` §1: the same function at the same state."""
    for state_id in STATE_IDS:
        state = REFERENCE.states[state_id]
        problem, context, x = compiled_at(state)
        residual = problem.residual(x, context)  # type: ignore[attr-defined]
        jacobian = problem.jacobian(x, context)  # type: ignore[attr-defined]
        for field_name in ("model_version", "constants_sha256", "state_sha256"):
            assert getattr(residual, field_name) == getattr(jacobian, field_name), state_id


def test_states_differing_only_in_pinned_inputs_share_a_model_version() -> None:
    """ADR 0008 D4.1 on the real fixture: structure identifies, pinned inputs distinguish."""
    versions = set()
    hashes = set()
    for state_id in STATE_IDS:
        problem, _, _ = compiled_at(REFERENCE.states[state_id])
        versions.add(problem.metadata.model_version)  # type: ignore[attr-defined]
        hashes.add(problem.metadata.constants_sha256)  # type: ignore[attr-defined]
    # ADR 0002 D2.3: one model_version, and its structure digest recomputes from the metadata.
    assert len(versions) == 1
    label, digest = split_model_version(next(iter(versions)))
    assert label == LABEL_L
    problem, _, _ = compiled_at(REFERENCE.states[STATE_IDS[0]], "L")
    metadata = problem.metadata  # type: ignore[attr-defined]
    assert digest == structure_sha256(
        metadata.variable_ids,
        metadata.equation_ids,
        metadata.parameter_ids,
        metadata.row_accumulation,
    )
    distinct_parameters = {
        tuple(
            sorted(
                (key, value)
                for key, value in (
                    ("feed_A", state.parameters.feed[0]),
                    ("feed_B", state.parameters.feed[1]),
                    ("feed_C", state.parameters.feed[2]),
                    ("h_feed", state.parameters.h_feed),
                    ("t_spec", state.parameters.t_spec),
                    ("p_spec", state.parameters.p_spec),
                )
            )
        )
        for state in (REFERENCE.states[state_id] for state_id in STATE_IDS)
    }
    assert len(hashes) == len(distinct_parameters), (
        "every distinct pinned-input vector must get its own constants_sha256, and two states "
        "sharing one must share the hash"
    )


def test_the_metadata_declares_what_the_boundary_promises() -> None:
    problem, _, _ = compiled_at(REFERENCE.states["S1"])
    metadata = problem.metadata  # type: ignore[attr-defined]
    assert metadata.backend == "casadi"
    assert metadata.variable_ids == closed_form.VARIABLE_IDS_L
    assert metadata.equation_ids == closed_form.EQUATION_IDS_L
    assert metadata.parameter_ids == PARAMETER_IDS
    assert set(metadata.row_accumulation) == set(closed_form.EQUATION_IDS_L)
    assert set(metadata.row_accumulation.values()) == {"algebraic"}
    assert metadata.capabilities.jacobian == "exact_sparse_csc"
    assert (metadata.capabilities.jvp, metadata.capabilities.vjp) == ("exact", "exact")
    assert metadata.capabilities.hessian == "absent"


def test_the_declared_block_sparsity_is_the_physical_one() -> None:
    """Six structural zeros in block H, and they are a claim about the physics.

    An enthalpy output depends on its own component's liquid flow and on the two intensive inputs.
    If that ever becomes untrue the assembled pattern changes, so the claim is asserted where it is
    made rather than only where its consequence shows up.
    """
    assert len(KBlock().jacobian_pattern()) == 6
    pattern = set(HBlock().jacobian_pattern())
    assert len(pattern) == 9
    for row in range(3):
        assert (row, row) in pattern
        assert {(row, 3), (row, 4)} <= pattern
        for other in range(3):
            if other != row:
                assert (row, other) not in pattern


@pytest.mark.parametrize(
    ("temperature", "pressure"),
    [(270.0, 100000.0), (450.0, 100000.0), (360.0, 40000.0), (360.0, 250000.0)],
)
def test_a_state_outside_the_domain_is_reported_not_extrapolated(
    temperature: float, pressure: float
) -> None:
    """The K block's domain is closed; leaving it is `invalid_trial_state`, never a number."""
    state = REFERENCE.states["S1"]
    problem, context, x = compiled_at(state)
    outside = x.copy()
    outside[closed_form.VARIABLE_IDS_L.index("T")] = temperature
    outside[closed_form.VARIABLE_IDS_L.index("P")] = pressure

    result = problem.residual(outside, context)  # type: ignore[attr-defined]
    assert result.status == "invalid_trial_state"
    assert result.values is None
    assert "outside" in result.message
    assert problem.jacobian(outside, context).status == "invalid_trial_state"  # type: ignore[attr-defined]


def test_the_inlined_form_really_composes_the_callback_derivative() -> None:
    """Anti-vacuity for adding form I at all.

    Form I earns its place only if a block output is composed with a *non-unit* outer derivative
    somewhere. If every appearance were still a ±1 pass-through, the extra fixture would double the
    test count and prove nothing new. The check is structural rather than numerical: in form I no
    variable named `lnK_*` or `hL_*` exists, so the blocks cannot be reaching the system through a
    definitional row, and `d(eq_i)/dT` must be nonzero — which it is only through the chain rule,
    since `T` enters `eq_i` by no other path.
    """
    state = REFERENCE.states["S5"]
    inlined = syn001_spec(state.parameters, form="I")
    assert not [name for name in inlined.variable_ids if name.startswith(("lnK_", "hL_"))]

    problem, context, x = compiled_at(state, "I")
    entries = jacobian_entries(problem.jacobian(x, context))  # type: ignore[attr-defined]
    for component in ("A", "B", "C"):
        assert abs(entries[f"eq_{component}|T"]) > 0.0, (
            f"d(eq_{component})/dT is zero in the inlined form; the only path from T to that row "
            "is through the K block's derivative, so a zero here means the chain rule is not "
            "being composed and this fixture proves nothing the lifted one did not"
        )

    # And in the lifted form that entry does not exist at all — which is the gap being closed.
    lifted, lifted_context, lifted_x = compiled_at(state, "L")
    lifted_entries = jacobian_entries(lifted.jacobian(lifted_x, lifted_context))  # type: ignore[attr-defined]
    assert "eq_A|T" not in lifted_entries
