"""Reference values and executable self-claims for the T08 build-first specification.

``docs/derivations/T08-build-first-spec.md`` registers (Part A) the dimensional realization of T04's
preregistered case PTC-R1 on a kinetic CSTR with holdup, the comparison that judges V14 (b) on it,
and (Part B) the compatible warm starts that judge V13 (e). Every number that document states about
PTC-R1 is re-derived here, and the script refuses to emit when one of its claims fails (spec §C.2).

Emitted, and labelled as such in the YAML:

* ``case`` -- the preregistered dimensionless case (T04 spec §8.4) and the registered dimensional
  realization, with the exact identities that map one onto the other (rational arithmetic).
* ``closed_form`` -- mpmath at 40 significant digits, written to 20: the three steady states in both
  coordinates, the physical Jacobian's eigenvalues, the finite generalized eigenvalues of the
  dimensional PTC pencil, the step-matrix singularity at the saddle, the single-step identities
  between the dimensional and dimensionless PTC and Newton steps at three off-grid states, the
  reaction-consistent reference invariance, and the numbers the classification radius is argued
  from.
* ``float64`` -- measured floors: the central-difference derivative floor of the dimensional rows.
* ``geometry`` -- the physical dynamics' separatrix (the saddle's stable manifold) and the basin
  label of every registered start under the physical dynamics (scipy, float64, written to six
  significant digits). These describe the physical ODE, never PTC or Newton: this script iterates
  neither method from any registered start (spec §A4.6).
* ``starts`` -- the 441 registered starts in dimensional coordinates, as exact binary64 values.
* ``criterion`` -- the resolved comparison criterion, the two comparison policies and the budgets.
* ``assertions`` -- the numbered-assertion catalogue, cross-checked against the specification.

It imports nothing from ``process_runtime`` or ``benchmarks`` (it reads committed files as data), so
none of its expectations comes from the code under judgement.

Amendment 1 (spec, 2026-09-29): the realization carries the third SYN-001 component ``C`` as an
inert trace (``2^-10`` mol/s, taken from ``A``'s feed), because the binder admits only ``(A, B, C)``
(ADR 0014 D9) and a component carried at exactly zero sits on its lower bound, where factorization
roundoff meets the bound rule (spec Amendment 1, Q1). The dimensional model is therefore six by six;
the claims of T08.B28 prove the trace inert, and every dimensionless number is unchanged.

Run from the repository root inside the project environment::

    python docs/derivations/scripts/t08_build_first_reference.py --check
    python docs/derivations/scripts/t08_build_first_reference.py \
        --emit benchmarks/t08/build_first_reference.yaml

``--check`` re-derives every claim and requires the committed YAML to equal the regenerated bytes.
``--emit`` is byte-reproducible.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
from collections.abc import Callable, Sequence
from fractions import Fraction
from pathlib import Path
from typing import Any

import numpy as np
import yaml
from mpmath import exp, findroot, lu_solve, matrix, mp, mpf, nstr, polyroots
from scipy.integrate import solve_ivp

mp.dps = 40

ROOT = Path(__file__).resolve().parents[3]
SPEC = ROOT / "docs" / "derivations" / "T08-build-first-spec.md"
YAML_PATH = ROOT / "benchmarks" / "t08" / "build_first_reference.yaml"
T04_YAML = ROOT / "benchmarks" / "t04" / "reference_values.yaml"
COMPONENTS_YAML = ROOT / "benchmarks" / "syn001" / "components.yaml"

# ---------------------------------------------------------------------------------------------
# 1. The preregistered case (T04 spec §8.4) and its dimensional realization (spec §A1.5).
# ---------------------------------------------------------------------------------------------

#: PTC-R1 exactly as T04 §8.4 registered it.
CASE_DA = Fraction(72, 1000)
CASE_B = Fraction(8)
CASE_BETA = Fraction(3, 10)
CASE_LE = Fraction(1)
GRID_N = 21
GRID_X1 = (Fraction(0), Fraction(1))
GRID_X2 = (Fraction(0), Fraction(8))
#: T04 §8.4's quoted steady-state temperatures and saddle numbers (six or four digits).
T04_QUOTED_X2 = ("1.050778", "1.490217", "5.935976")
T04_QUOTED_SADDLE = ("-0.9227", "0.2405")
T04_QUOTED_SINGULARITY = "4.16"

#: The trace of the third component (spec Amendment 1, Q1): exact in binary64, taken from A.
TRACE_C = Fraction(1, 1024)

#: The registered realization (spec §A1.5 as amended by Amendment 1, §A2). Decimal strings are the
#: revision's values.
REALIZATION: dict[str, str] = {
    "components": "A,B,C",
    "feed_A_mol_s": "0.4990234375",
    "feed_B_mol_s": "0.5",
    "feed_C_mol_s": "0.0009765625",
    "feed_T_K": "360",
    "feed_P_Pa": "100000",
    "nu_A": "1",
    "nu_B": "-1",
    "nu_C": "0",
    "key_component": "B",
    "phase": "vapor",
    "damkohler": "0.072",
    "T_ref_K": "360",
    "T_scale_K": "3.125",
    "coolant_flow_mol_s": "0.3",
    "coolant_cp_J_molK": "100",
    "T_coolant_K": "360",
    "pressure_drop_Pa": "0",
    "theta_s": "1",
}

#: The provider's declared domain (SYN-001 §1).
DOMAIN_T = (Fraction(280), Fraction(440))
DOMAIN_P = (Fraction(50000), Fraction(200000))

#: Region stop-test tolerances by quantity kind (ADR 0018 D2's quotation of KIND_TOLERANCE).
TOL_FLOW = mpf("3.1e-8")
TOL_HEAT = mpf("1.01e-3")

#: The classification radius (spec §A4.3), dimensionless infinity norm.
R_CLASS = mpf("2e-3")

#: Off-grid states for the single-step identities (spec §A5): none is a grid point.
OFF_GRID = (("0.12", "0.7"), ("0.33", "2.1"), ("0.905", "6.3"))
STEP_DTAUS = ("0.5", "4", "1000000")


def fr(key: str) -> Fraction:
    return Fraction(REALIZATION[key])


def mp_of(key: str) -> Any:
    return mpf(REALIZATION[key])


def mq(x: Fraction) -> Any:
    return mpf(x.numerator) / x.denominator


class Claims:
    def __init__(self) -> None:
        self.results: list[tuple[str, bool, str]] = []

    def check(self, name: str, ok: bool, detail: str = "") -> None:
        self.results.append((name, bool(ok), detail))

    @property
    def failed(self) -> list[tuple[str, bool, str]]:
        return [r for r in self.results if not r[1]]


def s20(x: Any) -> str:
    return str(nstr(x, 20, min_fixed=-5, max_fixed=8))


# ---------------------------------------------------------------------------------------------
# 2. SYN-001 data, read from the committed component records.
# ---------------------------------------------------------------------------------------------


def syn001(claims: Claims) -> dict[str, dict[str, Fraction]]:
    doc = yaml.safe_load(COMPONENTS_YAML.read_text(encoding="utf-8"))
    out: dict[str, dict[str, Fraction]] = {}
    for record in doc["components"]:
        p = record["parameters"]
        out[record["id"]] = {
            "L": Fraction(str(p["vapor_reference_enthalpy_offset"]["value"])),
            "cp": Fraction(str(p["heat_capacity"]["value"])),
            "Tb": Fraction(str(p["reference_boiling_temperature"]["value"])),
            "v": Fraction(str(p["liquid_molar_volume"]["value"])),
        }
    expected = {"A": (25000, 100, 320), "B": (30000, 100, 360), "C": (35000, 100, 400)}
    for c, (lat, cp, tb) in expected.items():
        claims.check(
            f"B01.syn001_record_{c}",
            out[c]["L"] == lat and out[c]["cp"] == cp and out[c]["Tb"] == tb,
            str(out.get(c)),
        )
    return out


T_R = Fraction(300)
P_R = Fraction(100000)
R_GAS = mpf("8.31446261815324")

# ---------------------------------------------------------------------------------------------
# 3. The exact identities of the realization (spec §A1.5).
# ---------------------------------------------------------------------------------------------


def identities(claims: Claims, data: dict[str, dict[str, Fraction]]) -> dict[str, Any]:
    cp = data["A"]["cp"]
    claims.check("B01.equal_cp", data["A"]["cp"] == data["B"]["cp"] == data["C"]["cp"], "")
    n_tot = fr("feed_A_mol_s") + fr("feed_B_mol_s") + fr("feed_C_mol_s")
    z_key = fr("feed_B_mol_s") / n_tot
    nu_a, nu_b, nu_c = fr("nu_A"), fr("nu_B"), fr("nu_C")
    # ADR 0011 D2: sum nu_i L_i
    dh_vap = nu_a * data["A"]["L"] + nu_b * data["B"]["L"] + nu_c * data["C"]["L"]
    # Amendment 1 (Q1): C is a trace taken from A, so the total feed stays exactly 1 mol/s and
    # B, beta and T_s are the registered ones.
    claims.check("B28.trace_value", fr("feed_C_mol_s") == TRACE_C, str(fr("feed_C_mol_s")))
    claims.check(
        "B28.trace_taken_from_A",
        fr("feed_A_mol_s") == Fraction(1, 2) - TRACE_C and n_tot == 1,
        str(n_tot),
    )
    claims.check("B28.trace_inert_stoichiometry", nu_c == 0, str(nu_c))
    b_real = -dh_vap * z_key / (cp * fr("T_scale_K"))
    beta_real = fr("coolant_flow_mol_s") * fr("coolant_cp_J_molK") / (n_tot * cp)
    da_real = fr("damkohler")  # times exp((T_f - T_ref)/T_s) = exp(0) = 1
    claims.check("B01.T_ref_equals_feed", fr("T_ref_K") == fr("feed_T_K"), "")
    claims.check("B01.coolant_at_feed", fr("T_coolant_K") == fr("feed_T_K"), "")
    claims.check("B01.Da", da_real == CASE_DA, str(da_real))
    claims.check("B01.B", b_real == CASE_B, str(b_real))
    claims.check("B01.beta", beta_real == CASE_BETA, str(beta_real))
    claims.check("B01.mass_conserving", nu_a + nu_b + nu_c == 0, "")
    claims.check("B01.exothermic", dh_vap == -5000, str(dh_vap))
    # binary64 facts the registered starts rely on
    claims.check("B01.ua_binary64_exact", 0.3 * 100.0 == 30.0, repr(0.3 * 100.0))
    claims.check(
        "B01.grid_flow_sums_exact",
        all((20 + i) / 40 + (20 - i) / 40 == 1.0 for i in range(GRID_N)),
        "",
    )
    trace = float(TRACE_C)
    claims.check(
        "B01.feed_sums_exact",
        0.4990234375 + 0.5 + trace == 1.0 and Fraction(0.4990234375) == fr("feed_A_mol_s"),
        "",
    )
    # every start's n_A = fl((20 + i)/40) - 2^-10 is exact, and n_A + n_B + n_C sums to 1.0
    claims.check(
        "B01.start_A_exact",
        all(
            Fraction((20 + i) / 40 - trace) == Fraction((20 + i) / 40) - TRACE_C
            for i in range(GRID_N)
        ),
        "",
    )
    claims.check(
        "B01.start_flow_sums_exact",
        all(((20 + i) / 40 - trace) + (20 - i) / 40 + trace == 1.0 for i in range(GRID_N)),
        "",
    )
    claims.check("B01.T_step_exact", float(fr("T_scale_K") * Fraction(2, 5)) == 1.25, "")
    exponent_max = (DOMAIN_T[1] - fr("T_ref_K")) / fr("T_scale_K")
    claims.check("B01.exponent_bound", exponent_max <= 700, str(exponent_max))
    return {
        "Da": str(da_real),
        "B": str(b_real),
        "beta": str(beta_real),
        "Le": str(CASE_LE),
        "delta_h_reaction_vapor_J_mol": str(dh_vap),
        "key_feed_fraction": str(z_key),
        "total_feed_mol_s": str(n_tot),
        "trace_C_mol_s": str(float(TRACE_C)),
        "UA_equivalent_W_K": str(fr("coolant_flow_mol_s") * fr("coolant_cp_J_molK")),
        "energy_scale_W": str(n_tot * cp * fr("T_scale_K")),
        "exponent_at_domain_top": str(exponent_max),
        "x2_of_T": "(T - 360 K) / 3.125 K",
        "x1_of_nB": "1 - n_B / 0.5 mol/s",
    }


# ---------------------------------------------------------------------------------------------
# 4. Closed forms (mpmath, 40 digits).
# ---------------------------------------------------------------------------------------------

DA_M, B_M, BETA_M = mpf(72) / 1000, mpf(8), mpf(3) / 10


def f_dimless(x1: Any, x2: Any) -> list[Any]:
    r = DA_M * (1 - x1) * exp(x2)
    return [-x1 + r, -x2 + B_M * r - BETA_M * x2]


def a_dimless(x1: Any, x2: Any) -> Any:
    e = DA_M * exp(x2)
    return matrix(
        [[-1 - e, (1 - x1) * e], [-B_M * e, -1 - BETA_M + B_M * (1 - x1) * e]],
    )


def steady_states() -> list[tuple[Any, Any]]:
    def g(x2: Any) -> Any:
        return (1 + BETA_M) * x2 - B_M * DA_M * exp(x2) / (1 + DA_M * exp(x2))

    out = []
    for guess in ("1.0", "1.5", "6.0"):
        x2 = findroot(g, mpf(guess))
        x1 = DA_M * exp(x2) / (1 + DA_M * exp(x2))
        out.append((x1, x2))
    return out


def eig2(a: Any) -> list[Any]:
    tr = a[0, 0] + a[1, 1]
    dt = a[0, 0] * a[1, 1] - a[0, 1] * a[1, 0]
    disc = tr * tr - 4 * dt
    return sorted([(tr - mp.sqrt(disc)) / 2, (tr + mp.sqrt(disc)) / 2])


class Dimensional:
    """The kinetic CSTR's rows on the registered realization (spec §A1.2, Amendment 1), columns
    (n_A, n_B, n_C, T, P, Q), rows (CSTR-mole:A, CSTR-mole:B, CSTR-mole:C, CSTR-duty,
    CSTR-cooling, CSTR-pressure). Index 2 is the trace component; `minor` deletes it."""

    SIGMA = (-1, -1, -1, -1, 1, 1)  # PTC_ROW_SIGN: holdup_balance -1, algebraic +1
    N = 6
    C = 2  # the trace component's row and column

    def __init__(self, data: dict[str, dict[str, Fraction]], ref_shift: tuple[Any, ...]) -> None:
        self.cp = mq(data["A"]["cp"])
        self.lat = tuple(mq(data[c]["L"]) + ref_shift[i] for i, c in enumerate("ABC"))
        self.n_in = (mp_of("feed_A_mol_s"), mp_of("feed_B_mol_s"), mp_of("feed_C_mol_s"))
        self.t_in, self.p_in = mp_of("feed_T_K"), mp_of("feed_P_Pa")
        self.nu = (mp_of("nu_A"), mp_of("nu_B"), mp_of("nu_C"))
        self.da, self.t_ref, self.t_s = mp_of("damkohler"), mp_of("T_ref_K"), mp_of("T_scale_K")
        self.ua = mp_of("coolant_flow_mol_s") * mp_of("coolant_cp_J_molK")
        self.t_c, self.dp = mp_of("T_coolant_K"), mp_of("pressure_drop_Pa")
        self.theta = mp_of("theta_s")

    def h(self, i: int, t: Any) -> Any:
        return self.cp * (t - mq(T_R)) + self.lat[i]

    def rate(self, x: Sequence[Any]) -> Any:
        return self.da * exp((x[3] - self.t_ref) / self.t_s) * x[1]

    def state(self, x1: Any, x2: Any) -> list[Any]:
        nb = self.n_in[1] * (1 - x1)
        na = self.n_in[0] + self.n_in[1] * x1
        t = self.t_in + self.t_s * x2
        return [na, nb, self.n_in[2], t, self.p_in - self.dp, self.ua * (self.t_c - t)]

    def rows(self, x: Sequence[Any]) -> list[Any]:
        r = self.rate(x)
        h_in = sum(self.n_in[i] * self.h(i, self.t_in) for i in range(3))
        h_out = sum(x[i] * self.h(i, x[3]) for i in range(3))
        return [
            self.n_in[0] - x[0] + self.nu[0] * r,
            self.n_in[1] - x[1] + self.nu[1] * r,
            self.n_in[2] - x[2] + self.nu[2] * r,
            x[5] + h_in - h_out,
            x[5] - self.ua * (self.t_c - x[3]),
            x[4] - self.p_in + self.dp,
        ]

    def jac(self, x: Sequence[Any]) -> Any:
        e = self.da * exp((x[3] - self.t_ref) / self.t_s)
        r = e * x[1]
        j = matrix(6, 6)
        for i in range(3):
            j[i, i] = -1
            j[i, 1] += self.nu[i] * e
            j[i, 3] = self.nu[i] * r / self.t_s
            j[3, i] = -self.h(i, x[3])
        j[3, 3], j[3, 5] = -self.cp * (x[0] + x[1] + x[2]), 1
        j[4, 3], j[4, 5] = self.ua, 1
        j[5, 4] = 1
        return j

    def mass(self, x: Sequence[Any]) -> Any:
        m = matrix(6, 6)
        for i in range(3):
            m[i, i] = self.theta
            m[3, i] = self.theta * self.h(i, x[3])
        m[3, 3] = self.theta * self.cp * (x[0] + x[1] + x[2])
        return m

    def signed(self, x: Sequence[Any]) -> tuple[list[Any], Any]:
        f = self.rows(x)
        j = self.jac(x)
        fs = [self.SIGMA[i] * f[i] for i in range(6)]
        js = matrix(6, 6)
        for i in range(6):
            for k in range(6):
                js[i, k] = self.SIGMA[i] * j[i, k]
        return fs, js

    def step(self, x: Sequence[Any], dtau: Any | None) -> list[Any]:
        """(M/dtau + J_sigma) d = -F_sigma; dtau None is Newton's step J d = -F."""
        fs, js = self.signed(x)
        a = js.copy()
        if dtau is not None:
            m = self.mass(x)
            for i in range(6):
                for k in range(6):
                    a[i, k] += m[i, k] / dtau
        d = lu_solve(a, matrix([-v for v in fs]))
        return [d[i] for i in range(6)]

    def to_dimless(self, d: Sequence[Any]) -> tuple[Any, Any]:
        return (-d[1] / self.n_in[1], d[3] / self.t_s)

    @classmethod
    def minor(cls, a: Any) -> Any:
        """`a` without the trace component's row and column."""
        keep = [i for i in range(cls.N) if i != cls.C]
        out = matrix(cls.N - 1, cls.N - 1)
        for r, i in enumerate(keep):
            for c, k in enumerate(keep):
                out[r, c] = a[i, k]
        return out

    def pencil_det(self, x: Sequence[Any], s: Any, *, reduced: bool) -> Any:
        _, js = self.signed(x)
        m = self.mass(x)
        a = js.copy()
        for i in range(6):
            for k in range(6):
                a[i, k] += s * m[i, k]
        return mp.det(self.minor(a) if reduced else a)

    def trace_factor_error(self, x: Sequence[Any]) -> Any:
        """B28: det(J_sigma + s M) = (1 + s theta) det(minor) at five values of s, relative."""
        worst = mpf(0)
        for s in (mpf(0), mpf("0.5"), mpf(1), mpf(2), mpf(-3)):
            full = self.pencil_det(x, s, reduced=False)
            factored = (1 + s * self.theta) * self.pencil_det(x, s, reduced=True)
            worst = max(worst, abs(full - factored) / max(abs(full), abs(factored)))
        return worst

    def pencil(self, x: Sequence[Any]) -> list[Any]:
        """Finite s with det(J_sigma + s M) = 0. The trace row factors out (1 + s theta) (B28), so
        the roots are those of the minor's determinant, a cubic (rank M = 3 there), and -1/theta."""
        pts = [mpf(k) for k in range(5)]
        vals = [self.pencil_det(x, p, reduced=True) for p in pts]
        # Newton divided differences -> monomial coefficients (degree <= 4)
        n = len(pts)
        coef = list(vals)
        for lvl in range(1, n):
            for i in range(n - 1, lvl - 1, -1):
                coef[i] = (coef[i] - coef[i - 1]) / (pts[i] - pts[i - lvl])
        poly = [mpf(0)] * n  # poly[k] = coefficient of s^k
        basis = [mpf(1)] + [mpf(0)] * (n - 1)
        for i in range(n):
            for k in range(n):
                poly[k] += coef[i] * basis[k]
            nxt = [mpf(0)] * n
            for k in range(n - 1):
                nxt[k + 1] += basis[k]
                nxt[k] -= pts[i] * basis[k]
            basis = nxt
        self.quartic = abs(poly[4]) / max(abs(p) for p in poly)
        roots = polyroots(list(reversed(poly[:4])), maxsteps=200, extraprec=200)
        return sorted([mp.re(r) for r in roots] + [-1 / self.theta])

    def step_det(self, x: Sequence[Any], dtau: Any) -> Any:
        _, js = self.signed(x)
        m = self.mass(x)
        a = js.copy()
        for i in range(6):
            for k in range(6):
                a[i, k] += m[i, k] / dtau
        return mp.det(a)


def closed_forms(claims: Claims, data: dict[str, dict[str, Fraction]]) -> dict[str, Any]:
    dim = Dimensional(data, (mpf(0), mpf(0), mpf(0)))
    roots = steady_states()
    names = ("LOW", "MID", "HIGH")
    t04 = yaml.safe_load(T04_YAML.read_text(encoding="utf-8"))["closed_form"][
        "ptc_r1_cstr_preregistered"
    ]
    out_roots: dict[str, Any] = {}
    residual_max = mpf(0)
    pencil_err = mpf(0)
    quartic_max = mpf(0)
    factor_err = mpf(0)
    trace_row_max = mpf(0)
    inv_norms: dict[str, Any] = {}
    for idx, (name, (x1, x2)) in enumerate(zip(names, roots, strict=True)):
        fd = f_dimless(x1, x2)
        claims.check(f"B02.{name}_dimless_root", max(abs(v) for v in fd) < mpf("1e-35"), "")
        ev = eig2(a_dimless(x1, x2))
        reg = t04["steady_states"][idx]
        claims.check(
            f"B02.{name}_vs_T04",
            abs(x1 - mpf(reg["x1"])) < mpf("1e-11")
            and abs(x2 - mpf(reg["x2"])) < mpf("1e-10")
            and all(
                abs(e - mpf(r)) < mpf("1e-14")
                for e, r in zip(ev, sorted(mpf(v) for v in reg["eigenvalues"]), strict=True)
            ),
            f"{s20(x1)} {s20(x2)}",
        )
        claims.check(
            f"B02.{name}_quoted_T04_8_4",
            nstr(x2, 7) == T04_QUOTED_X2[idx],
            str(nstr(x2, 7)),
        )
        x = dim.state(x1, x2)
        f = dim.rows(x)
        residual_max = max(residual_max, max(abs(v) for v in f))
        trace_row_max = max(trace_row_max, abs(f[Dimensional.C]))
        factor_err = max(factor_err, dim.trace_factor_error(x))
        pen = dim.pencil(x)
        quartic_max = max(quartic_max, dim.quartic)
        # physical modes, the total-moles mode and the trace's mode (Amendment 1)
        expected = sorted(ev + [-1 / dim.theta, -1 / dim.theta])
        pencil_err = max(pencil_err, max(abs(a - b) for a, b in zip(pen, expected, strict=True)))
        a = a_dimless(x1, x2)
        dt = a[0, 0] * a[1, 1] - a[0, 1] * a[1, 0]
        inv = matrix([[a[1, 1] / dt, -a[0, 1] / dt], [-a[1, 0] / dt, a[0, 0] / dt]])
        inv_inf = max(abs(inv[i, 0]) + abs(inv[i, 1]) for i in range(2))
        inv_norms[name] = inv_inf
        out_roots[name] = {
            "x1": s20(x1),
            "x2": s20(x2),
            "n_A_mol_s": s20(x[0]),
            "n_B_mol_s": s20(x[1]),
            "n_C_mol_s": s20(x[2]),
            "T_K": s20(x[3]),
            "P_Pa": s20(x[4]),
            "Q_W": s20(x[5]),
            "physical_eigenvalues_per_theta": [s20(e) for e in ev],
            "pencil_finite_eigenvalues_per_s": [s20(e) for e in pen],
            "stable": all(e < 0 for e in ev),
        }
    claims.check("B03.dimensional_rows_vanish", residual_max < mpf("1e-30"), s20(residual_max))
    claims.check("B03.pencil_is_physical_plus_two_unit_modes", pencil_err < mpf("1e-25"), "")
    claims.check("B28.trace_row_vanishes_at_roots", trace_row_max == 0, s20(trace_row_max))
    claims.check("B28.trace_mode_factors_out", factor_err < mpf("1e-30"), s20(factor_err))
    claims.check("B03.pencil_det_is_cubic", quartic_max < mpf("1e-25"), s20(quartic_max))
    claims.check(
        "B03.stability_pattern",
        [out_roots[n]["stable"] for n in names] == [True, False, True],
        "",
    )

    # the saddle: singularity, contraction threshold, determinant sign change
    x1m, x2m = roots[1]
    s_minus, s_plus = eig2(a_dimless(x1m, x2m))
    dtau_star = dim.theta / s_plus
    xm = dim.state(x1m, x2m)
    d_lo = dim.step_det(xm, dtau_star * (1 - mpf("1e-3")))
    d_hi = dim.step_det(xm, dtau_star * (1 + mpf("1e-3")))
    d_at = dim.step_det(xm, dtau_star)
    claims.check("B03.singular_at_dtau_star", abs(d_at) < mpf("1e-30") * abs(d_lo), s20(d_at))
    claims.check("B03.det_sign_change", d_lo * d_hi < 0, "")
    claims.check(
        "B03.quoted_T04_singularity",
        nstr(dtau_star, 3) == T04_QUOTED_SINGULARITY
        and nstr(s_minus, 4) == T04_QUOTED_SADDLE[0]
        and nstr(s_plus, 4) == T04_QUOTED_SADDLE[1],
        f"{nstr(dtau_star, 6)} {nstr(s_minus, 6)} {nstr(s_plus, 6)}",
    )
    claims.check("B03.tau0_below_singularity", mpf(1) < dtau_star, "")

    # single-step identities at off-grid states (B04)
    step_err = mpf(0)
    steps: list[dict[str, Any]] = []
    grid_x2 = {Fraction(8 * j, 20) for j in range(GRID_N)}
    grid_x1 = {Fraction(i, 20) for i in range(GRID_N)}
    for sx1, sx2 in OFF_GRID:
        claims.check(
            f"B04.off_grid_{sx1}_{sx2}",
            Fraction(sx1) not in grid_x1 and Fraction(sx2) not in grid_x2,
            "",
        )
        x1, x2 = mpf(sx1), mpf(sx2)
        x = dim.state(x1, x2)
        fvec = f_dimless(x1, x2)
        a = a_dimless(x1, x2)
        row: dict[str, Any] = {"x1": sx1, "x2": sx2}
        for label, dt in [*((f"ptc_dtau_{d}", mpf(d)) for d in STEP_DTAUS), ("newton", None)]:
            dd = dim.to_dimless(dim.step(x, dt))
            aa = a.copy()
            if dt is not None:
                aa[0, 0] -= dim.theta / dt
                aa[1, 1] -= dim.theta / dt
            # dimensionless: (theta/dtau I - A) d = f
            ref = lu_solve(-aa, matrix(fvec))
            err = max(abs(dd[0] - ref[0]), abs(dd[1] - ref[1])) / max(abs(ref[0]), abs(ref[1]))
            step_err = max(step_err, err)
            full = dim.step(x, dt)
            claims.check(
                f"B04.total_moles_and_algebraic_{sx1}_{sx2}_{label}",
                abs(full[0] + full[1] + full[2]) < mpf("1e-35")
                and abs(full[4]) < mpf("1e-35")
                and abs(full[5] + dim.ua * full[3]) < mpf("1e-30"),
                "",
            )
            claims.check(
                f"B28.trace_step_zero_{sx1}_{sx2}_{label}", abs(full[2]) < mpf("1e-35"), ""
            )
            row[label] = {"d_x1": s20(ref[0]), "d_x2": s20(ref[1])}
            row[label + "_dimensional"] = {
                "d_n_A": s20(full[0]),
                "d_n_B": s20(full[1]),
                "d_n_C": s20(full[2]),
                "d_T": s20(full[3]),
                "d_P": s20(full[4]),
                "d_Q": s20(full[5]),
            }
        steps.append(row)
    claims.check("B04.step_identity", step_err < mpf("1e-30"), s20(step_err))

    # reference invariance (B05): a reaction-consistent shift leaves the step unchanged
    shifted = Dimensional(data, (mpf(1000), mpf(1000), mpf(1000)))
    inv_err = mpf(0)
    for sx1, sx2 in OFF_GRID:
        x = dim.state(mpf(sx1), mpf(sx2))
        for d in STEP_DTAUS:
            a0, a1 = dim.step(x, mpf(d)), shifted.step(x, mpf(d))
            inv_err = max(inv_err, max(abs(u - v) for u, v in zip(a0, a1, strict=True)))
    claims.check("B05.reaction_consistent_shift_invariant", inv_err < mpf("1e-30"), s20(inv_err))
    skew = Dimensional(data, (mpf(0), mpf(1000), mpf(0)))
    moved = skew.rows(dim.state(roots[0][0], roots[0][1]))
    claims.check(
        "B05.inconsistent_shift_changes_the_problem",
        abs(moved[3]) > mpf(1),
        s20(moved[3]),
    )

    # classification radius argument (B09)
    r1 = TOL_FLOW / mp_of("feed_B_mol_s")
    r2 = (2 * TOL_HEAT + abs(dim.lat[1] - dim.lat[0]) * TOL_FLOW) / (
        (dim.n_in[0] + dim.n_in[1] + dim.n_in[2]) * dim.cp * dim.t_s
    )
    worst = max(inv_norms.values()) * max(r1, r2)
    sep = min(
        max(abs(roots[i][0] - roots[k][0]), abs(roots[i][1] - roots[k][1]))
        for i in range(3)
        for k in range(i + 1, 3)
    )
    claims.check("B09.radius_above_accuracy", R_CLASS >= 10 * worst, s20(worst))
    claims.check("B09.radius_below_separation", R_CLASS <= sep / 100, s20(sep))

    return {
        "steady_states": out_roots,
        "saddle": {
            "s_minus_per_theta": s20(s_minus),
            "s_plus_per_theta": s20(s_plus),
            "dtau_singular_over_theta": s20(dtau_star),
            "dtau_contracting_over_theta": s20(2 * dtau_star),
            "unstable_direction_factor": "1 / (1 - s_plus * dtau)",
        },
        "single_steps": steps,
        "single_step_max_relative_difference": s20(step_err),
        "trace_mode_factor_max_relative_error": s20(factor_err),
        "reference_shift_max_step_difference": s20(inv_err),
        "classification": {
            "radius_dimensionless_inf_norm": str(R_CLASS),
            "residual_bound_x1_row": s20(r1),
            "residual_bound_x2_row": s20(r2),
            "inverse_jacobian_inf_norm": {k: s20(v) for k, v in inv_norms.items()},
            "distance_bound": s20(worst),
            "min_root_separation": s20(sep),
        },
    }


# ---------------------------------------------------------------------------------------------
# 5. Admissibility and domain margins (B06), measured derivative floor (B12).
# ---------------------------------------------------------------------------------------------


def dew_point(data: dict[str, dict[str, Fraction]], z_b: Any, p: Any) -> Any:
    """The outlet's dew point at key fraction `z_b`, with the trace C at its feed fraction and A
    the rest (the outlet's composition along x1, since n_tot = 1 and C is inert)."""

    def k(c: str, t: Any) -> Any:
        rec = data[c]
        return (mq(P_R) / p) * exp(
            (mq(rec["L"]) / R_GAS) * (1 / mq(rec["Tb"]) - 1 / t)
            + mq(rec["v"]) * (p - mq(P_R)) / (R_GAS * t)
        )

    z_c = mq(TRACE_C)
    z_a = 1 - z_c - z_b
    return findroot(lambda t: z_a / k("A", t) + z_b / k("B", t) + z_c / k("C", t) - 1, mpf(340))


def two_component_dew_point(data: dict[str, dict[str, Fraction]], z_b: Any, p: Any) -> Any:
    """The C_reg realization's dew point (no C), kept only to bound the trace's shift."""

    def k(c: str, t: Any) -> Any:
        rec = data[c]
        return (mq(P_R) / p) * exp(
            (mq(rec["L"]) / R_GAS) * (1 / mq(rec["Tb"]) - 1 / t)
            + mq(rec["v"]) * (p - mq(P_R)) / (R_GAS * t)
        )

    return findroot(lambda t: (1 - z_b) / k("A", t) + z_b / k("B", t) - 1, mpf(340))


def margins(claims: Claims, data: dict[str, dict[str, Fraction]]) -> dict[str, Any]:
    p = mp_of("feed_P_Pa")
    z_bs = [mpf(k) / 200 for k in range(0, 101)]  # z_B from 0 to 0.5 (x1 from 1 to 0)
    # Amendment 1: the trace moves the dew point by less than 1 K (the claim bounds it)
    shift = dew_point(data, mpf("0.5"), p) - two_component_dew_point(data, mpf("0.5"), p)
    claims.check("B28.trace_dew_shift_below_1K", 0 < shift < 1, s20(shift))
    dews = [dew_point(data, z, p) for z in z_bs]
    dew_max = max(dews)
    claims.check("B06.dew_max_at_feed", dews.index(dew_max) == len(dews) - 1, "")
    t_min_grid = mp_of("feed_T_K")
    t_s = mp_of("T_scale_K")
    claims.check("B06.grid_superheated", t_min_grid - dew_max > 10, s20(t_min_grid - dew_max))
    # physical trajectories from the grid: 0 <= x2 <= max(x2_0 + B (1 - x1_0), B) <= 16
    x2_bound = CASE_B + max(GRID_X2[1], CASE_B)
    t_top = fr("feed_T_K") + fr("T_scale_K") * x2_bound
    claims.check("B06.trajectory_bound_in_domain", t_top < DOMAIN_T[1], str(t_top))
    claims.check("B06.pressure_in_domain", DOMAIN_P[0] < fr("feed_P_Pa") < DOMAIN_P[1], "")
    return {
        "dew_point_max_K": s20(dew_max),
        "dew_point_shift_by_trace_K": s20(shift),
        "dew_point_max_x2": s20((dew_max - t_min_grid) / t_s),
        "grid_T_range_K": [str(fr("feed_T_K")), str(fr("feed_T_K") + 8 * fr("T_scale_K"))],
        "trajectory_x2_bound": str(x2_bound),
        "trajectory_T_bound_K": str(t_top),
        "domain_top_x2": str((DOMAIN_T[1] - fr("feed_T_K")) / fr("T_scale_K")),
    }


FEED64 = (0.4990234375, 0.5, 0.0009765625)
LAT64 = (25000.0, 30000.0, 35000.0)


def rows64(x: Sequence[float]) -> list[float]:
    """The registered rows in binary64, as an implementation would evaluate them; columns
    (n_A, n_B, n_C, T, P, Q)."""
    cp = 100.0
    r = 0.072 * math.exp((x[3] - 360.0) / 3.125) * x[1]
    h_in = sum(FEED64[i] * (cp * 60.0 + LAT64[i]) for i in range(3))
    h_out = sum(x[i] * (cp * (x[3] - 300.0) + LAT64[i]) for i in range(3))
    return [
        FEED64[0] - x[0] + r,
        FEED64[1] - x[1] - r,
        FEED64[2] - x[2] + 0.0 * r,
        x[5] + h_in - h_out,
        x[5] - 30.0 * (360.0 - x[3]),
        x[4] - 100000.0,
    ]


ROW_NAMES = (
    "CSTR-mole:A",
    "CSTR-mole:B",
    "CSTR-mole:C",
    "CSTR-duty",
    "CSTR-cooling",
    "CSTR-pressure",
)
COL_NAMES = ("n_A", "n_B", "n_C", "T", "P", "Q")


def model_values(claims: Claims, data: dict[str, dict[str, Fraction]]) -> dict[str, Any]:
    """What the implementation must reproduce at the registered roots (B11-B13, B18, B19), and
    the binary64 floors the tolerances of B11 and B15 are argued from."""
    dim = Dimensional(data, (mpf(0), mpf(0), mpf(0)))
    out: dict[str, Any] = {}
    floor_mole, floor_heat = 0.0, 0.0
    for name, (x1, x2) in zip(("LOW", "MID", "HIGH"), steady_states(), strict=True):
        x = dim.state(x1, x2)
        j, m = dim.jac(x), dim.mass(x)
        f64 = rows64([float(v) for v in x])
        floor_mole = max(floor_mole, abs(f64[0]), abs(f64[1]), abs(f64[2]))
        floor_heat = max(floor_heat, abs(f64[3]), abs(f64[4]))
        claims.check(f"B11.pressure_row_exact_{name}", f64[5] == 0.0, repr(f64[5]))
        claims.check(f"B28.trace_row_exact_binary64_{name}", f64[2] == 0.0, repr(f64[2]))
        heat = (dim.lat[1] - dim.lat[0]) * dim.rate(x)
        out[name] = {
            "jacobian_nonzeros": {
                f"{ROW_NAMES[r]}|{COL_NAMES[c]}": s20(j[r, c])
                for r in range(6)
                for c in range(6)
                if j[r, c] != 0
            },
            "mass_nonzeros_theta_1s": {
                f"{ROW_NAMES[r]}|{COL_NAMES[c]}": s20(m[r, c])
                for r in range(6)
                for c in range(6)
                if m[r, c] != 0
            },
            "reaction_heat_in_duty_row_W": s20(heat),
        }
        claims.check(f"B11.reaction_heat_catchable_{name}", heat > 400, s20(heat))
    tol_mole, tol_heat = 1e-12, 1e-8
    claims.check("B11.mole_tolerance_margin", tol_mole >= 100 * floor_mole, repr(floor_mole))
    claims.check("B11.heat_tolerance_margin", tol_heat >= 100 * floor_heat, repr(floor_heat))
    # step conditioning at the off-grid states (B15)
    cond_max = mpf(0)
    for sx1, sx2 in OFF_GRID:
        a = a_dimless(mpf(sx1), mpf(sx2))
        for d in [*STEP_DTAUS, None]:
            aa = -a.copy()
            if d is not None:
                aa[0, 0] += 1 / mpf(d)
                aa[1, 1] += 1 / mpf(d)
            dt = aa[0, 0] * aa[1, 1] - aa[0, 1] * aa[1, 0]
            inv = matrix([[aa[1, 1] / dt, -aa[0, 1] / dt], [-aa[1, 0] / dt, aa[0, 0] / dt]])
            nrm = max(abs(aa[i, 0]) + abs(aa[i, 1]) for i in range(2))
            nrm_inv = max(abs(inv[i, 0]) + abs(inv[i, 1]) for i in range(2))
            cond_max = max(cond_max, nrm * nrm_inv)
    claims.check("B15.tolerance_above_floor", mpf("1e-8") >= 1e3 * 2.2e-16 * cond_max, "")
    # the causal initializer at the registered feed (B18) and the liquid variant (B19)
    nb0 = mpf("0.5") / (1 + mpf("0.072"))
    na0 = 1 - mq(TRACE_C) - nb0  # n_in,A + (n_in,B - n_B): the trace is taken from A
    return {
        "at_roots": out,
        "binary64_row_floor_at_rounded_roots": {
            "mole_mol_s": f"{floor_mole:.2e}",
            "heat_W": f"{floor_heat:.2e}",
        },
        "tolerances": {"mole_mol_s": "1e-12", "heat_W": "1e-8", "pressure_Pa": "0 (exact)"},
        "off_grid_step_condition_max": s20(cond_max),
        "causal_initializer_at_feed": {
            "n_A_mol_s": s20(na0),
            "n_B_mol_s": s20(nb0),
            "n_C_mol_s": str(float(TRACE_C)),
            "T_K": "360",
            "P_Pa": "100000",
            "Q_W": "0",
            "x1": s20(1 - nb0 / mpf("0.5")),
        },
        "liquid_variant_root": {
            "inputs": "as the realization with phase liquid and feed, T_ref, T_coolant at 300 K",
            "n_A_mol_s": s20(na0),
            "n_B_mol_s": s20(nb0),
            "n_C_mol_s": str(float(TRACE_C)),
            "T_K": "300 (exact)",
            "Q_W": "0 (exact)",
            "reaction_heat_W": "0 (exact: ADR 0011 D2, liquid reactions are thermoneutral)",
        },
    }


def derivative_floor(claims: Claims, data: dict[str, dict[str, Fraction]]) -> dict[str, Any]:
    """Central differences of `rows64`, relative step 1e-6 of the registered nominal of each
    column's kind (flow 3 mol/s, temperature 100 K, pressure 1e5 Pa, heat rate 1e5 W), against
    the closed-form Jacobian; the error of an entry is normalized by its row's largest entry."""
    dim = Dimensional(data, (mpf(0), mpf(0), mpf(0)))
    nominal = (3.0, 3.0, 3.0, 100.0, 1.0e5, 1.0e5)
    states = [dim.state(x1, x2) for x1, x2 in steady_states()]
    states += [dim.state(mpf(a), mpf(b)) for a, b in OFF_GRID]
    worst = 0.0
    for x in states:
        xf = [float(v) for v in x]
        j = dim.jac(x)
        for col in range(6):
            h = 1e-6 * nominal[col]
            up, dn = list(xf), list(xf)
            up[col] += h
            dn[col] -= h
            fu, fd = rows64(up), rows64(dn)
            for row in range(6):
                scale = max(abs(float(j[row, k])) for k in range(6))
                fd_val = (fu[row] - fd[row]) / (2 * h)
                worst = max(worst, abs(fd_val - float(j[row, col])) / scale)
    claims.check("B12.fd_floor_measured", 0 < worst < 1e-9, repr(worst))
    return {
        "relative_step_of_nominal": "1e-6",
        "stencil": "central, second order",
        "measured_floor_row_normalized": f"{worst:.2e}",
        "registered_tolerance": "1e-7",
        "margin_over_floor": f"{1e-7 / worst:.0f}",
    }


# ---------------------------------------------------------------------------------------------
# 6. The registered starts (B07) and the physical dynamics' geometry (B08).
# ---------------------------------------------------------------------------------------------


def starts(claims: Claims) -> tuple[list[list[Any]], str]:
    rows: list[list[Any]] = []
    for j in range(GRID_N):
        for i in range(GRID_N):
            n_a, n_b = (20 + i) / 40 - float(TRACE_C), (20 - i) / 40
            t = 360.0 + 1.25 * j
            q = 30.0 * (360.0 - t)
            rows.append([i, j, repr(n_a), repr(n_b), repr(t), repr(q)])
    keys = {tuple(r[2:]) for r in rows}
    claims.check("B07.count", len(rows) == GRID_N * GRID_N, "")
    claims.check("B07.distinct", len(keys) == len(rows), "")
    claims.check(
        "B07.map_exact",
        all(
            Fraction(float(r[4])) == 360 + Fraction(25, 8) * Fraction(8 * r[1], 20)
            and float(r[5]) == -37.5 * r[1]
            for r in rows
        ),
        "",
    )
    # Amendment 1: every start's C column sits 2^-10 mol/s above its bound, more than 1e9 times
    # the unit roundoff at the registered flow nominal (3 mol/s); the factorization roundoff the
    # design lane measured on those columns at §A5's six states is at most 2.3e-16 mol/s.
    claims.check(
        "B28.trace_far_above_roundoff",
        float(TRACE_C) >= 1e9 * 2.0**-52 * 3.0 and float(TRACE_C) >= 1e12 * 2.3e-16,
        repr(float(TRACE_C)),
    )
    digest = hashlib.sha256(json.dumps(rows, separators=(",", ":")).encode("ascii")).hexdigest()
    return rows, digest


DA_F, B_F, BETA_F = 0.072, 8.0, 0.3


def ode(t: float, x: Sequence[float]) -> list[float]:
    r = DA_F * (1.0 - x[0]) * math.exp(x[1])
    return [-x[0] + r, -x[1] + B_F * r - BETA_F * x[1]]


def ode_jac(t: float, x: Sequence[float]) -> list[list[float]]:
    e = DA_F * math.exp(x[1])
    return [[-1.0 - e, (1.0 - x[0]) * e], [-B_F * e, -1.0 - BETA_F + B_F * (1.0 - x[0]) * e]]


def geometry(claims: Claims, roots: dict[str, Any]) -> dict[str, Any]:
    low = (float(roots["LOW"]["x1"]), float(roots["LOW"]["x2"]))
    mid = (float(roots["MID"]["x1"]), float(roots["MID"]["x2"]))
    high = (float(roots["HIGH"]["x1"]), float(roots["HIGH"]["x2"]))

    # the saddle's stable manifold, by backward integration from the saddle
    a = np.array(ode_jac(0.0, mid))
    w, v = np.linalg.eig(a)
    vs = v[:, int(np.argmin(w.real))].real

    def back(t: float, x: Sequence[float]) -> list[float]:
        f = ode(t, x)
        return [-f[0], -f[1]]

    def back_jac(t: float, x: Sequence[float]) -> list[list[float]]:
        j = ode_jac(t, x)
        return [[-j[0][0], -j[0][1]], [-j[1][0], -j[1][1]]]

    def leave(t: float, x: Sequence[float]) -> float:
        return min(x[0] + 1e-9, 1.0 + 1e-9 - x[0], x[1] + 1.0, 9.0 - x[1])

    leave.terminal = True  # type: ignore[attr-defined]
    branches = []
    for sign in (1.0, -1.0):
        x0 = [mid[0] + sign * 1e-9 * vs[0], mid[1] + sign * 1e-9 * vs[1]]
        sol = solve_ivp(
            back,
            (0.0, 200.0),
            x0,
            method="Radau",
            jac=back_jac,
            rtol=1e-12,
            atol=1e-14,
            events=leave,
            dense_output=True,
            max_step=0.05,
        )
        claims.check(f"B08.branch_{int(sign)}_left_box", sol.status == 1, str(sol.status))
        branches.append(sol)

    crossings: list[float] = []
    for i in range(GRID_N):
        xi = i / 20
        found: list[float] = []
        for sol in branches:
            y = sol.y
            for k in range(len(sol.t) - 1):
                lo, hi = y[0, k] - xi, y[0, k + 1] - xi
                if lo == 0.0 or lo * hi < 0.0:
                    ta, tb = sol.t[k], sol.t[k + 1]
                    for _ in range(80):
                        tm = 0.5 * (ta + tb)
                        if (sol.sol(ta)[0] - xi) * (sol.sol(tm)[0] - xi) <= 0.0:
                            tb = tm
                        else:
                            ta = tm
                    found.append(float(sol.sol(ta)[1]))
        if i == 0 and not found:  # the branch ends on x1 = 0 (the event), take its end
            for sol in branches:
                if abs(sol.y[0, -1]) < 1e-6:
                    found.append(float(sol.y[1, -1]))
        claims.check(f"B08.one_crossing_column_{i}", len(found) == 1, str(found))
        crossings.append(found[0] if found else float("nan"))

    # physical basin label of every start (forward integration)
    def near(target: tuple[float, float]) -> Callable[[float, Sequence[float]], float]:
        def ev(t: float, x: Sequence[float]) -> float:
            return max(abs(x[0] - target[0]), abs(x[1] - target[1])) - 1e-3

        ev.terminal = True  # type: ignore[attr-defined]
        return ev

    labels: list[str] = []
    x2_max = 0.0
    min_vertical = math.inf
    for j in range(GRID_N):
        row = ""
        for i in range(GRID_N):
            x0 = [i / 20, 0.4 * j]
            sol = solve_ivp(
                ode,
                (0.0, 400.0),
                x0,
                method="LSODA",
                jac=ode_jac,
                rtol=1e-9,
                atol=1e-12,
                events=(near(low), near(high)),
            )
            x2_max = max(x2_max, float(sol.y[1].max()))
            lab = "L" if sol.t_events[0].size else ("H" if sol.t_events[1].size else "?")
            row += lab
            side = "H" if 0.4 * j > crossings[i] else "L"
            claims.check(f"B08.label_matches_side_{i}_{j}", lab == side, f"{lab} {side}")
            min_vertical = min(min_vertical, abs(0.4 * j - crossings[i]))
        labels.append(row)
    claims.check("B08.no_start_near_manifold", min_vertical >= 1e-3, repr(min_vertical))
    claims.check("B08.trajectory_bound", x2_max <= 16.0, repr(x2_max))
    counts = {"L": sum(r.count("L") for r in labels), "H": sum(r.count("H") for r in labels)}
    claims.check("B08.both_basins_present", counts["L"] > 0 and counts["H"] > 0, str(counts))
    return {
        "method": (
            "stable manifold: Radau backward from the saddle +/- 1e-9 along the stable "
            "eigenvector, rtol 1e-12; labels: LSODA forward, rtol 1e-9, stopped within 1e-3 "
            "of a stable root"
        ),
        "separatrix_x2_at_grid_columns": [f"{c:.6f}" for c in crossings],
        "min_vertical_distance_start_to_separatrix": f"{min_vertical:.3e}",
        "max_x2_along_physical_trajectories": f"{x2_max:.4f}",
        "physical_basin_labels_rows_j0_to_j20": labels,
        "physical_basin_counts": counts,
    }


# ---------------------------------------------------------------------------------------------
# 7. The resolved criterion, the comparison policies and budgets (spec §A4).
# ---------------------------------------------------------------------------------------------

CRITERION: dict[str, Any] = {
    "classes": {
        "LOW": "solve outcome CONVERGED and final state within the radius of the LOW root",
        "MID": "solve outcome CONVERGED and final state within the radius of the MID root",
        "HIGH": "solve outcome CONVERGED and final state within the radius of the HIGH root",
        "FAIL": "any other outcome, or CONVERGED and within no root's radius",
    },
    "distance": "max(|x1 - x1*|, |x2 - x2*|), x1 = 1 - n_B/0.5, x2 = (T - 360)/3.125",
    "reached_set": "S_a = { starts g : class_a(g) in {LOW, HIGH} }",
    "b1_containment": "PASS iff there is a start g with g in S_ptc and g not in S_newton",
    "saddle_clause": "PASS iff class_ptc(g) != MID for every one of the 441 starts",
    "mechanism": "T08.B14: the implementation's step matrix at the saddle is singular at "
    "dtau = theta / s_plus",
    "route_a": "T08.B11-B15 pass",
    "arms": {
        "newton": "T06-revision-v2 with globalization.eo_core = newton, eo_recovery = none",
        "ptc": "T06-revision-v2 with globalization.eo_core = ptc, eo_recovery = none, "
        "ptc = T04 spec 7.7 constants",
    },
    "budgets": {
        "newton_max_iterations_per_attempt": 50,
        "ptc_max_steps_per_attempt": 200,
        "max_attempts": 5,
        "max_property_calls": None,
        "wall_time": None,
    },
    "tolerances": "the region's KIND_TOLERANCE rows (unchanged); no tolerance is added",
    "start_entry": "execute_plan(user_start=<start over every spec.variable_ids>), T06 W6",
    "trace_component": "C at 2^-10 mol/s in the feed and every start (S1.n.C = S2.n.C = "
    "0.0009765625); every run ends with S1.n.C and S2.n.C within 1e-12 mol/s of it and no "
    "rejection names a C column (T08.B21, Amendment 1)",
}


# ---------------------------------------------------------------------------------------------
# 8. The assertion catalogue (spec §C.1).
# ---------------------------------------------------------------------------------------------

ASSERTIONS: dict[str, tuple[str, str]] = {
    "T08.B00": ("this generator's --check", "generator"),
    "T08.B01": ("realization identities Da, B, beta, Le and binary64 facts", "generator"),
    "T08.B02": ("steady states and physical eigenvalues, against T04's registration", "generator"),
    "T08.B03": ("dimensional rows, pencil, and the saddle's step singularity", "generator"),
    "T08.B04": ("dimensional and dimensionless steps agree off the grid", "generator"),
    "T08.B05": ("reaction-consistent reference invariance of the step", "generator"),
    "T08.B06": ("admissibility and domain margins", "generator"),
    "T08.B07": ("the 441 registered starts", "generator"),
    "T08.B08": ("physical separatrix, basin labels, no start on the manifold", "generator"),
    "T08.B09": ("classification radius argument", "generator"),
    "T08.B10": ("kinetic CSTR contract and construction refusals", "test"),
    "T08.B11": ("kinetic CSTR rows at the registered roots", "test"),
    "T08.B12": ("kinetic CSTR Jacobian: closed form and central differences", "test"),
    "T08.B13": ("mass-mapping entries and V1-V4 on the CSTR region", "test"),
    "T08.B14": ("implementation pencil and step singularity at the saddle", "test"),
    "T08.B15": ("implementation single steps at the off-grid states", "test"),
    "T08.B16": ("zero flow and the adiabatic limit", "test"),
    "T08.B17": ("out-of-domain temperatures end typed", "test"),
    "T08.B18": ("causal evaluator is the isothermal local initializer", "test"),
    "T08.B19": ("liquid variant is thermoneutral; vapour is not", "test"),
    "T08.B20": ("case registered before any PTC-R1 result (git order)", "verdict"),
    "T08.B21": ("the 882 comparison runs, classified", "ci"),
    "T08.B22": ("V14 (b1) containment on PTC-R1", "verdict"),
    "T08.B23": ("the saddle clause", "verdict"),
    "T08.B24": ("PTC selectable through the contract on PTC-R1 (b3)", "test"),
    "T08.B25": ("SER tests at the RC (b4)", "ci"),
    "T08.B26": ("registered identities unchanged", "ci"),
    "T08.B27": ("envelope updated: model, policies, U07", "test"),
    "T08.B28": ("the trace component C is inert and off its bound (Amendment 1)", "generator"),
    "T08.B40": ("warm start absent: identical to the cold run", "test"),
    "T08.B41": ("warm start accepted and recorded", "test"),
    "T08.B42": ("warm start never changes the problem", "test"),
    "T08.B43": ("structurally incompatible candidate rejected to the next source", "test"),
    "T08.B44": ("tampered candidate rejected", "test"),
    "T08.B45": ("candidate failing evaluation rejected", "test"),
    "T08.B46": ("bounds projection logged, not rejected", "test"),
    "T08.B47": ("warm-started bundles replay from the bundle alone", "test"),
    "T08.B48": ("the selection rule", "test"),
    "T08.B49": ("policies without the source are byte-identical", "test"),
    "T08.B50": ("agent surface unchanged (T08.A49 digests)", "ci"),
    "T08.B51": ("V13 (e) verdict", "verdict"),
}


#: Amendment 1 (spec, 2026-09-29): the rows its §Am1.C table replaces, and the rows it adds.
AMENDMENT_1_MARKER = "\n# Amendment 1"
AMENDED_1 = frozenset(
    "T08.B" + n
    for n in ("01", "03", "04", "06", "07", "13", "14", "17", "18", "20", "21", "41", "42")
    + ("46", "50")
)
ADDED_1 = frozenset({"T08.B28"})


def catalogue(claims: Claims) -> dict[str, Any]:
    text = SPEC.read_text(encoding="utf-8") if SPEC.exists() else ""
    claims.check("B00.spec_present", bool(text), str(SPEC))
    body, marker, amendment = text.partition(AMENDMENT_1_MARKER)
    claims.check("B00.amendment_1_present", bool(marker), "")
    pattern = r"^\| (T08\.B\d\d) \|"
    in_spec = re.findall(pattern, body, flags=re.M)
    in_amendment = re.findall(pattern, amendment, flags=re.M)
    for label, ids in (("spec", in_spec), ("amendment_1", in_amendment)):
        claims.check(
            f"B00.{label}_ids_unique",
            len(ids) == len(set(ids)),
            str(sorted({i for i in ids if ids.count(i) > 1})),
        )
        claims.check(f"B00.{label}_order", ids == sorted(ids), "")
    claims.check(
        "B00.amendment_1_rows_are_registered",
        set(in_amendment) == AMENDED_1 | ADDED_1
        and AMENDED_1 <= set(in_spec)
        and not ADDED_1 & set(in_spec),
        f"{sorted(set(in_amendment) ^ (AMENDED_1 | ADDED_1))}",
    )
    claims.check(
        "B00.spec_equals_catalogue",
        set(in_spec) | set(in_amendment) == set(ASSERTIONS),
        f"spec only {sorted((set(in_spec) | set(in_amendment)) - set(ASSERTIONS))}; "
        f"catalogue only {sorted(set(ASSERTIONS) - set(in_spec) - set(in_amendment))}",
    )
    claims.check("B00.no_T08_A_ids", not re.search(r"^\| T08\.A\d\d \|", text, flags=re.M), "")
    return {
        k: {
            "subject": s,
            "judged_by": j,
            **({"amended": "Amendment 1"} if k in AMENDED_1 else {}),
            **({"added": "Amendment 1"} if k in ADDED_1 else {}),
        }
        for k, (s, j) in ASSERTIONS.items()
    }


def build(claims: Claims) -> dict[str, Any]:
    data = syn001(claims)
    cf = closed_forms(claims, data)
    rows, digest = starts(claims)
    return {
        "schema_version": 1,
        "generator": "docs/derivations/scripts/t08_build_first_reference.py",
        "specification": "docs/derivations/T08-build-first-spec.md",
        "precision": "mpmath 40 significant digits, written to 20; geometry float64, 6 digits",
        "independence": "imports nothing from process_runtime or benchmarks; reads committed files",
        "amendments": [
            {
                "id": "Amendment 1",
                "date": "2026-09-29",
                "before": "C_case (no PTC-R1 result exists)",
                "changes": "components (A, B, C) with C an inert 2^-10 mol/s trace taken from A; "
                "B17, B41, B42 and the carried V17 oracle restated; see the spec",
            }
        ],
        "case": {
            "preregistered": {
                "source": "docs/derivations/T04-globalization-spec.md 8.4",
                "Da": str(CASE_DA),
                "B": str(CASE_B),
                "beta": str(CASE_BETA),
                "Le": str(CASE_LE),
                "grid": "21 x 21 on [0, 1] x [0, 8], x1 = i/20, x2 = 0.4 j",
            },
            "realization": dict(REALIZATION),
            "identities": identities(claims, data),
        },
        "closed_form": cf,
        "margins": margins(claims, data),
        "model": model_values(claims, data),
        "float64": {"derivative_floor": derivative_floor(claims, data)},
        "geometry": geometry(claims, cf["steady_states"]),
        "starts": {
            "columns": ["i", "j", "n_A_mol_s", "n_B_mol_s", "T_K", "Q_W"],
            "fixed": {
                "n_C_mol_s": str(float(TRACE_C)),
                "P_Pa": "100000",
                "feed": "every feed coordinate at its fixed value (S1.n.C = 0.0009765625)",
            },
            "sha256_of_compact_json": digest,
            "rows": rows,
        },
        "criterion": CRITERION,
        "assertions": catalogue(claims),
    }


class _Dumper(yaml.SafeDumper):
    pass


def _flow_lists(dumper: yaml.SafeDumper, data: list[Any]) -> yaml.Node:
    flow = all(not isinstance(v, dict | list) for v in data) and len(data) <= 8
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=flow)


_Dumper.add_representer(list, _flow_lists)


def dump(data: dict[str, Any]) -> str:
    header = (
        "# Generated by docs/derivations/scripts/t08_build_first_reference.py -- do not edit.\n"
        "# Re-derive with --check; regenerate with --emit.\n"
    )
    return header + yaml.dump(data, Dumper=_Dumper, sort_keys=False, allow_unicode=True, width=100)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="re-derive every claim and compare with the committed YAML",
    )
    parser.add_argument("--emit", metavar="PATH", help="write the reference YAML")
    args = parser.parse_args(argv)
    if not args.check and not args.emit:
        parser.error("choose --check and/or --emit PATH")
    claims = Claims()
    text = dump(build(claims))
    for name, ok, detail in claims.results:
        if not ok:
            print(f"FAIL {name}: {detail}")
    print(f"{len(claims.results) - len(claims.failed)} of {len(claims.results)} claims pass")
    if claims.failed:
        return 1
    data = text.encode("utf-8")
    if args.check:
        committed = YAML_PATH.read_bytes() if YAML_PATH.exists() else b""
        same = committed == data
        print(
            f"committed YAML {'equals' if same else 'DIFFERS FROM'} the regenerated bytes "
            f"(sha256 {hashlib.sha256(data).hexdigest()})"
        )
        if not same:
            return 1
    if args.emit:
        path = Path(args.emit)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"wrote {path} ({len(data)} bytes, sha256 {hashlib.sha256(data).hexdigest()})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
