"""Reference values and executable self-claims for the T08 release specification.

``docs/derivations/T08-release-spec.md`` makes claims about numbers and about the repository: which
evidence manifests it cites and what they contain, which registered digests the release candidate
must reproduce, the Clopper-Pearson bounds it quotes, the closed form of the verifier's
alias-pressure-shift limit, the scored real-chemistry dossier and its ranking, and the catalogue of
numbered assertions. Every one of those claims is re-derived here, and the script refuses to emit
when one fails (T08 spec §10).

Emitted, and labelled as such in the YAML:

* ``registered`` -- values read from committed repository files (manifests, the benchmark
  registry, the lock file), each compared against the literal the specification quotes. These are
  facts about the repository, not expectations derived from definitions.
* ``closed_form`` -- expectations derived from definitions: the one-sided 95 % Clopper-Pearson
  lower bounds (mpmath, 40 digits, written to 20) and the alias-shift position limit (exact
  rationals).
* ``dossier`` -- the V19 selection rubric, the candidate scores with their evidence labels, the
  totals, the ranking under the tie-break rule, and the sensitivity of the ranking to every
  provisional score. The scores are design-lane judgements; the arithmetic on them is checked.
* ``assertions`` -- the catalogue of numbered assertions, cross-checked against the
  specification's own table in both directions.

It imports nothing from ``process_runtime`` or ``benchmarks`` (it reads their committed files as
data), so none of its expectations comes from the code under judgement.

Run from the repository root inside the project environment::

    python docs/derivations/scripts/t08_reference.py --check
    python docs/derivations/scripts/t08_reference.py --emit benchmarks/t08/reference_values.yaml

``--check`` re-derives every claim and requires the committed YAML to equal the regenerated bytes.
``--emit`` is byte-reproducible.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import sys
from collections.abc import Sequence
from fractions import Fraction
from pathlib import Path
from typing import Any

import yaml
from mpmath import betainc, mp, mpf, nstr

mp.dps = 40

ROOT = Path(__file__).resolve().parents[3]
SPEC = ROOT / "docs" / "derivations" / "T08-release-spec.md"
YAML_PATH = ROOT / "benchmarks" / "t08" / "reference_values.yaml"

# ---------------------------------------------------------------------------------------------
# 1. The evidence manifests the specification cites (spec §3.1), with the tallies it quotes.
# ---------------------------------------------------------------------------------------------

#: package -> (commit prefix, status, {check result: count}) as quoted in spec §3.1.
CITED_MANIFESTS: dict[str, tuple[str, str, dict[str, int]]] = {
    "K02": ("1baaf03", "reviewed", {"pass": 19, "not_applicable": 1, "unsupported": 1}),
    "K03": ("c806f83", "reviewed", {"pass": 15, "not_applicable": 1, "unsupported": 1}),
    "K04": ("bf3d9ee", "reviewed", {"pass": 7, "not_applicable": 1, "unsupported": 1}),
    "K05": ("b0a7fe7", "reviewed", {"pass": 7, "unsupported": 1}),
    "K06": ("cda68cd", "reviewed", {"pass": 6, "not_applicable": 1, "unsupported": 1}),
    "P03": ("449cf3d", "reviewed", {"pass": 14, "not_applicable": 2, "unsupported": 2}),
    "T01": ("00a71f4", "tested", {"pass": 26}),
    "T02": ("b68585f", "tested", {"pass": 37}),
    "T03": ("6ac24be", "tested", {"pass": 27}),
    "T04": ("53cd23b", "tested", {"pass": 34}),
    "T05": ("91ac010", "tested", {"pass": 31}),
    "T05b": ("ba9a27b", "tested", {"pass": 64}),
    "T06": ("ebec629", "tested", {"pass": 96, "not_applicable": 4}),
    "T07": ("5f3d3ea", "tested", {"pass": 107}),
}

#: Registered digests the release candidate must reproduce (spec §3.2, §8), each with the committed
#: file that registers it.
REGISTERED_DIGESTS: dict[str, tuple[str, str]] = {
    "requirements_lock_sha256": (
        "ead4edf1ea3577287a7576d56a9e5db550e5a5be459dd634b10806fdc655b9c4",
        "evidence/T07/5f3d3ea25e8349b83c8f8382df3c793532971ca4/manifest.json",
    ),
    # Amendment R5 1: moved by ADR 0025 D1.2's recording switch, a substitution only (R-148); the
    # values T07 registered with v1 recorded are in REGISTERED_V1. Amendment R6 1: moved again by
    # the rename to `openflowsheet`, a substitution only (R-149); R-148's values are in
    # REGISTERED_PRE_RENAME.
    "k05_identity_minus_t07_sha256": (
        "24af004ab5718e559bd3d40716d66e21d9b19043a26777a39a0da84c6fbdcb8e",
        "tests/test_t07_identity.py",
    ),
    "structural_sha256": (
        "ed6d11f3beb78c6f1debc481c6e525ce3ccb120bd30cdfd07e470f728e082e90",
        "tests/test_t07_identity.py",
    ),
    "k05_identity_t07_key_sha256": (
        "887a2e622676dbfaff0a8ebfc309414f0e74150ace8327887b4a9ec15e498a38",
        "tests/test_t08_w1_identity_substitution.py",
    ),
    "v17_c2_tool_descriptions_sha256": (
        "6d13e13d660521c1a39dc245d5237c974a4273b0c3eeadb02d44538ba2669a4d",
        "benchmarks/t07/v17/runs/v17-c2/V17-T01-1/run.json",
    ),
    "t06_starts_nominal_sha256": (
        "3a7bd49c66493744753d1eac554101317c931e0ef51d9154d6f7cab3124fef82",
        "benchmarks/registry.yaml",
    ),
    # Amendment R3 2: the surface R-133 carries, which T08.A49 now requires.
    "t08_served_tool_descriptions_sha256": (
        "171dd768efcfb24f65d79d83a4f157dcfd1436935bf5106a247b84f3040e4d14",
        "tests/test_t08_w2_surface_digest.py",
    ),
}

#: Amendment R5 1 (c): each entry R-148 moved -> the value registered with v1 recorded, and the
#: committed file that registers it.
REGISTERED_V1: dict[str, tuple[str, str]] = {
    "k05_identity_minus_t07_sha256": (
        "9a7b4e6d1e794e903a41ba2bd96ead58a074896380d80e37e0f06545cff3d4bc",
        "tests/test_t07_identity.py",
    ),
    "structural_sha256": (
        "915c97e82551c75c588ec4a4e41b060241d75e037366c099c285493165a97e27",
        "evidence/T07/5f3d3ea25e8349b83c8f8382df3c793532971ca4/manifest.json",
    ),
    "k05_identity_t07_key_sha256": (
        "422aa7a5d1b50ea1ab5f101fe368fd51c108b463eb9d8a0af905f1e9bd09c122",
        "tests/test_t08_w1_identity_substitution.py",
    ),
}

#: Amendment R6 1: each entry R-149 moved -> the value reproduced before the rename (R5 1's), and
#: the committed file that registers it.
REGISTERED_PRE_RENAME: dict[str, tuple[str, str]] = {
    "k05_identity_minus_t07_sha256": (
        "29246e053ad126034c1aeef0f396ffe1d9f4dffcf5128f226720280bd1b656e5",
        "tests/test_t07_identity.py",
    ),
    "structural_sha256": (
        "e62a59a6b3634afd8f43eae399129a2d64bafb6e8ba90ad5fe0c9c1a9c5ad238",
        "tests/test_t07_identity.py",
    ),
    "k05_identity_t07_key_sha256": (
        "a96f17eda025168ea184584bd8f0fd2bed6d940ecf8356a6b7ee6f9663348e4b",
        "tests/test_t08_w1_identity_substitution.py",
    ),
}

#: Amendment R5 1 (b): entry -> the constant of the RC script (T08.A42) that must carry the same
#: value, so that the specification and the RC check cannot drift apart.
RC_SCRIPT = "scripts/t08_rc.py"
RC_CONSTANTS: dict[str, str] = {
    "k05_identity_minus_t07_sha256": "K05_MINUS_T07_SHA256",
    "k05_identity_t07_key_sha256": "T07_KEY_SHA256",
}

#: Amendment R5 1 (d): the register entry that must carry both values of each moved pair.
REGISTER = "docs/decision-register.md"
REGISTER_ENTRY = "R-148"
#: Amendment R6 1: the register entry that must carry both values of each pair R-149 moved.
REGISTER_ENTRY_R6 = "R-149"

#: The T06 ensemble gate as registered (benchmarks/registry.yaml `ensemble`), quoted in spec §4.10.
ENSEMBLE_GATE = {"N": 440, "S_min": 418, "machine_classes": ["ref-x86-64", "ci-aarch64"]}

# ---------------------------------------------------------------------------------------------
# 2. Closed forms.
# ---------------------------------------------------------------------------------------------

#: One-sided 95 % Clopper-Pearson lower bounds quoted in spec §4 (x of n), and the literal each
#: earlier verdict recorded where one exists (T06 verdict §2.2; T07 verdict §3.1; T06 manifest).
CP_POINTS: list[tuple[int, int, str | None]] = [
    (418, 440, None),
    (434, 440, "0.9732639029561057"),
    (436, 440, "0.979318"),
    (24, 30, None),
    (25, 30, "0.681029"),
]

#: ADR 0014 D5 / T06 spec §8.2: pressure column j (0-based position in `variable_ids`) is shifted
#: by s_j = 997 (j + 1) Pa, up if the provider domain admits P + s_j, else down if it admits
#: P - s_j, else the alias certificate is unsupported. SYN-001's domain is [5e4, 2e5] Pa inclusive.
ALIAS_BASE_PA = 997
P_LO, P_HI = 50_000, 200_000
ALIAS_PROBES = [50_000, 100_000, 125_000, 180_000, 200_000]


def cp_lower(x: int, n: int, alpha: str = "0.05") -> Any:
    """The p with P(X >= x | n, p) = alpha, i.e. I_p(x, n - x + 1) = alpha, by bisection."""
    a = mpf(alpha)
    lo, hi = mpf(0), mpf(x) / n
    for _ in range(200):
        mid = (lo + hi) / 2
        if betainc(x, n - x + 1, 0, mid, regularized=True) > a:
            hi = mid
        else:
            lo = mid
    return (lo + hi) / 2


def alias_direction(p: int, j: int) -> str:
    """The rule of ADR 0014 D5 at pressure `p` for column position `j`, in exact integers."""
    s = ALIAS_BASE_PA * (j + 1)
    if P_LO <= p + s <= P_HI:
        return "up"
    if P_LO <= p - s <= P_HI:
        return "down"
    return "unsupported"


def alias_jmax(p: int) -> int:
    """Largest j that is not unsupported at `p`: 997 (j + 1) <= max(P_HI - p, p - P_LO)."""
    room = Fraction(max(P_HI - p, p - P_LO))
    return int(room // ALIAS_BASE_PA) - 1


# ---------------------------------------------------------------------------------------------
# 3. The V19 dossier rubric (spec §7.2) and the candidate assessment (spec §7.3).
# ---------------------------------------------------------------------------------------------

HARD = {
    "H1": "reactor route: a steady PyMRM reactor model for the chemistry runs, or can be written "
    "from published equations with no new science",
    "H2": "kinetics: a published rate law with parameters, compared with experimental data",
    "H3": "needed nonideal property route: the loop's conditions need one, and a method and a "
    "parameter source are identified",
    "H4": "independent reference: an acquired tool (IDAES 2.13 or DWSIM) represents the loop "
    "skeleton with the selected method, or a published independent case exists",
    "H5": "rights: every code and data item has known rights compatible with modes A/C",
    "H6": "scope: steady-state VLE inside blueprint §2.2's v0.2 envelope (no electrolytes, "
    "solids, LLE or columns needed for the loop)",
}
HARD_VALUES = ("met", "needs_fact", "needs_frank", "fails")

SCORED = {
    "S1": (
        "Frank's group can provide the reactor model (plan §4.4 'prefer')",
        "2 found and runnable in the group's code; 1 group model named but not found; 0 none",
    ),
    "S2": (
        "reactor-separator-recycle native to the chemistry (blueprint §2.3)",
        "2 recycle with purge is how the process runs; 1 recycle needs a separation outside "
        "v0.2's units; 0 no recycle",
    ),
    "S3": (
        "a continuous design decision moved by reactor fidelity",
        "2 the decision changes qualitatively between fidelity levels; 1 quantitatively; "
        "0 not at all",
    ),
    "S4": (
        "independent simulator case",
        "2 a published case of the same chemistry exists in an acquired tool; 1 representable "
        "but must be built; 0 none",
    ),
    "S5": (
        "reactor validation data",
        "2 experimental data at hand, machine-readable; 1 in the literature; 0 none",
    ),
    "S6": (
        "M01 size (components, reactions, property route)",
        "2 <= 5 components, 1 reaction, one nonideal method; 1 <= 7 components or 2 "
        "independent reactions or two methods; 0 larger",
    ),
    "S7": (
        "computational cost of one reactor solve at design-loop resolution",
        "2 seconds; 1 minutes; 0 hours",
    ),
    "S8": ("reuse beyond v0.2 (W27 overlap, v0.3 columns)", "2 both; 1 one; 0 neither"),
}
#: Tie-break order (spec §7.2): S1 (plan's stated preference), then S2 (blueprint §2.3's journey),
#: then S4 (the reference route), then the candidate id.
TIE_BREAK = ("S1", "S2", "S4")

#: id -> label, hard statuses, scores {Sx: (score, provisional?)}. Provisional = rests on a fact
#: not yet measured (spec §7.3 marks it); the sensitivity table moves each over 0..2.
CANDIDATES: dict[str, dict[str, Any]] = {
    "C1": {
        "label": "ammonia synthesis loop (Ru-catalyst packed bed; the group's PyMRM model)",
        "hard": {
            "H1": "needs_fact",
            "H2": "needs_frank",
            "H3": "met",
            "H4": "needs_fact",
            "H5": "needs_frank",
            "H6": "met",
        },
        "scores": {
            "S1": (2, False),
            "S2": (2, False),
            "S3": (2, False),
            "S4": (1, False),
            "S5": (2, False),
            "S6": (2, False),
            "S7": (1, True),
            "S8": (0, False),
        },
    },
    "C2": {
        "label": "methanol synthesis loop (Cu/ZnO packed bed; literature kinetics)",
        "hard": {
            "H1": "met",
            "H2": "needs_fact",
            "H3": "met",
            "H4": "met",
            "H5": "met",
            "H6": "met",
        },
        "scores": {
            "S1": (0, True),
            "S2": (2, False),
            "S3": (2, False),
            "S4": (2, False),
            "S5": (1, False),
            "S6": (1, False),
            "S7": (1, True),
            "S8": (2, False),
        },
    },
    "C3": {
        "label": "ethylene glycol by ethylene-oxide hydration (liquid tubular reactor)",
        "hard": {
            "H1": "met",
            "H2": "needs_fact",
            "H3": "met",
            "H4": "met",
            "H5": "met",
            "H6": "needs_fact",
        },
        "scores": {
            "S1": (0, True),
            "S2": (1, False),
            "S3": (2, False),
            "S4": (2, False),
            "S5": (1, False),
            "S6": (2, False),
            "S7": (2, True),
            "S8": (1, False),
        },
    },
    "C4": {
        "label": "toluene hydrodealkylation (HDA) loop",
        "hard": {
            "H1": "met",
            "H2": "needs_fact",
            "H3": "needs_fact",
            "H4": "met",
            "H5": "met",
            "H6": "met",
        },
        "scores": {
            "S1": (0, True),
            "S2": (2, False),
            "S3": (1, False),
            "S4": (2, False),
            "S5": (1, False),
            "S6": (1, False),
            "S7": (2, True),
            "S8": (1, False),
        },
    },
    "C5": {
        "label": "steam methane reforming",
        "hard": {
            "H1": "met",
            "H2": "needs_fact",
            "H3": "needs_fact",
            "H4": "met",
            "H5": "met",
            "H6": "met",
        },
        "scores": {
            "S1": (0, True),
            "S2": (0, False),
            "S3": (1, False),
            "S4": (1, False),
            "S5": (1, False),
            "S6": (1, False),
            "S7": (1, True),
            "S8": (0, False),
        },
    },
}
RECOMMENDED, RUNNER_UP = "C1", "C2"


def total(scores: dict[str, tuple[int, bool]]) -> int:
    return sum(v for v, _ in scores.values())


def rank(cands: dict[str, dict[str, Any]]) -> list[str]:
    """Selectable candidates (no hard criterion `fails`) by total, then the tie-break keys."""
    selectable = [c for c, d in cands.items() if "fails" not in d["hard"].values()]

    def key(c: str) -> tuple[Any, ...]:
        s = cands[c]["scores"]
        return (-total(s), *(-s[k][0] for k in TIE_BREAK), c)

    return sorted(selectable, key=key)


def sensitivity(cands: dict[str, dict[str, Any]]) -> list[dict[str, Any]]:
    """For every provisional score, the top two at its extremes 0 and 2."""
    rows = []
    for c, d in cands.items():
        for s, (value, provisional) in d["scores"].items():
            if not provisional:
                continue
            tops = {}
            for trial in (0, 2):
                alt = json.loads(json.dumps(cands))
                alt[c]["scores"][s] = [trial, True]
                alt = {
                    k: {**v, "scores": {kk: tuple(vv) for kk, vv in v["scores"].items()}}
                    for k, v in alt.items()
                }
                tops[trial] = rank(alt)[:2]
            rows.append(
                {
                    "candidate": c,
                    "score": s,
                    "as_registered": value,
                    "top_two_at_0": tops[0],
                    "top_two_at_2": tops[2],
                    "moves_top": tops[0][0] != RECOMMENDED or tops[2][0] != RECOMMENDED,
                }
            )
    return rows


# ---------------------------------------------------------------------------------------------
# 4. The assertion catalogue (spec §9), cross-checked against the specification's table.
# ---------------------------------------------------------------------------------------------

#: id -> (subject, judged by). "generator": this script; "test": a pytest node the build lane
#: adds; "ci": a CI job's recorded output; "verdict": the `verdict` agent against §4.
ASSERTIONS: dict[str, tuple[str, str]] = {
    "T08.A00": ("this generator's --check", "generator"),
    "T08.A01": ("cited manifests: status and tallies", "generator"),
    "T08.A02": ("requirements ledger V11-V20 evidence and verdict provenance", "test"),
    "T08.A03": ("one verdict row per gate at the RC commit", "verdict"),
    "T08.A10": ("D1: invalid-structure report names the revision's own objects", "test"),
    "T08.A11": ("D2: replay identity carried by every bundle and certificate", "test"),
    "T08.A12": ("D3: failure-bundle counters equal the trace meter", "test"),
    "T08.A13": ("identity moves are substitutions only", "test"),
    "T08.A14": ("no untyped end reachable from a public operation", "test"),
    "T08.A15": ("A89 outcome on repeated aarch64 runs", "ci"),
    "T08.A16": ("campaign records carry commit, tree state, lock hash, machine class", "test"),
    "T08.A17": ("CLI replay --rerun reruns the recorded route or refuses typed", "test"),
    "T08.A18": ("both reviews of every MCP description recorded at the served hash", "test"),
    "T08.A19": ("lock lookup confined to the checkout; installed bundles replay NOT_RUN", "ci"),
    "T08.A20": ("envelope equals the code registries", "test"),
    "T08.A21": ("every manifest limitation classified exactly once", "test"),
    "T08.A22": ("every unsupported row has a passing typed-outcome test", "test"),
    "T08.A23": ("support matrix regenerates byte for byte", "test"),
    "T08.A24": ("alias-shift limit at its threshold states", "test"),
    "T08.A30": ("[A10] refresh on both architectures", "ci"),
    "T08.A31": ("mode A hygiene and notices", "test"),
    "T08.A32": ("data provenance of shipped records", "test"),
    "T08.A33": ("recovery-edge inventory bijection and direct tests", "test"),
    "T08.A34": ("rank evidence and energy qualification on every RC certificate", "ci"),
    "T08.A35": ("v0.0.0 bundle handled typed", "test"),
    "T08.A40": ("lock file unchanged", "generator"),
    "T08.A41": ("full gate green on both architectures at the RC", "ci"),
    "T08.A42": ("identity document at the RC", "ci"),
    "T08.A43": ("sdist and wheel contents and content reproducibility", "ci"),
    "T08.A44": ("clean install outside the tree solves and certifies", "ci"),
    "T08.A45": ("clean-environment replay of the RC bundle set", "ci"),
    "T08.A46": ("nominal ensemble at the RC on both machine classes", "ci"),
    "T08.A47": ("adversarial and invalid-structure suite at the RC", "ci"),
    "T08.A48": ("reference comparisons, our side, at the RC", "ci"),
    "T08.A49": ("V17 surface identity and scripted transports", "ci"),
    "T08.A50": ("the v0.1 gate report", "test"),
    "T08.A60": ("dossier completeness", "verdict"),
    "T08.A61": ("PyMRM reactor smoke", "ci"),
    "T08.A62": ("property-route smoke in the reference tool", "ci"),
    "T08.A63": ("reference representability smoke", "ci"),
    "T08.A64": ("rights table has no unknown", "verdict"),
    "T08.A65": ("dossier ranking recomputes", "generator"),
    "T08.A70": ("V14 qualified-PTC clause", "verdict"),
    "T08.A71": ("V13 warm-start clause", "verdict"),
}

GATES = ("V11", "V12", "V13", "V14", "V15", "V16", "V17", "V18", "V19", "V20")


# ---------------------------------------------------------------------------------------------
# Claims.
# ---------------------------------------------------------------------------------------------


class Claims:
    def __init__(self) -> None:
        self.results: list[tuple[str, bool, str]] = []

    def check(self, name: str, ok: bool, detail: str = "") -> None:
        self.results.append((name, bool(ok), detail))

    @property
    def failed(self) -> list[tuple[str, bool, str]]:
        return [r for r in self.results if not r[1]]


def sha256_file(rel: str) -> str:
    return hashlib.sha256((ROOT / rel).read_bytes()).hexdigest()


def manifest_facts(claims: Claims) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for pkg, (prefix, status, tallies) in CITED_MANIFESTS.items():
        found = sorted((ROOT / "evidence" / pkg).glob("*/manifest.json"))
        claims.check(f"A01.{pkg}.one_manifest", len(found) == 1, f"{len(found)} manifests")
        if len(found) != 1:
            continue
        m = json.loads(found[0].read_text(encoding="utf-8"))
        tally: dict[str, int] = {}
        for c in m["checks"]:
            r = c.get("result")
            tally[r] = tally.get(r, 0) + 1
        rel = found[0].relative_to(ROOT).as_posix()
        claims.check(f"A01.{pkg}.commit", m["commit"].startswith(prefix), m["commit"])
        claims.check(f"A01.{pkg}.status", m["status"] == status, m["status"])
        claims.check(f"A01.{pkg}.tallies", tally == tallies, str(tally))
        out[pkg] = {
            "path": rel,
            "status": m["status"],
            "checks": dict(sorted(tally.items())),
            "limitations": len(m.get("limitations", [])),
        }
    return out


#: Spec §5.7: the harvest's size today — manifests, and limitations in the two groups it quotes.
HARVEST_QUOTED = {"manifests": 18, "limitations_P00_K06": 87, "limitations_T01_T07": 145}


#: The packages whose manifests exist at the spec's writing; later manifests (T08's own, v0.2's)
#: are outside this claim, so they do not break it.
HARVEST_PACKAGES = (
    "P00",
    "P01",
    "P02",
    "P03",
    "K01",
    "K02",
    "K03",
    "K04",
    "K05",
    "K06",
    "T01",
    "T02",
    "T03",
    "T04",
    "T05",
    "T05b",
    "T06",
    "T07",
)


def harvest_counts(claims: Claims) -> dict[str, int]:
    found = sorted(
        f for pkg in HARVEST_PACKAGES for f in (ROOT / "evidence" / pkg).glob("*/manifest.json")
    )
    early, late = 0, 0
    for f in found:
        pkg = f.relative_to(ROOT).parts[1]
        n = len(json.loads(f.read_text(encoding="utf-8")).get("limitations", []))
        if pkg.startswith(("P", "K")):
            early += n
        else:
            late += n
    got = {"manifests": len(found), "limitations_P00_K06": early, "limitations_T01_T07": late}
    claims.check("A21.harvest_size_as_quoted", got == HARVEST_QUOTED, str(got))
    return got


def module_string_constants(rel: str) -> dict[str, str]:
    """A script's module-level string constants, read with `ast` (the script is not imported)."""
    tree = ast.parse((ROOT / rel).read_text(encoding="utf-8"), filename=rel)
    out: dict[str, str] = {}
    for node in tree.body:
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            targets, value = [node.target], node.value
        elif isinstance(node, ast.Assign):
            targets, value = [t for t in node.targets if isinstance(t, ast.Name)], node.value
        else:
            continue
        if isinstance(value, ast.Constant) and isinstance(value.value, str):
            out.update({t.id: value.value for t in targets})
    return out


def register_entry(entry: str) -> str:
    """The text of one entry of the decision register, from its heading to the next heading."""
    text = (ROOT / REGISTER).read_text(encoding="utf-8")
    m = re.search(rf"^## {re.escape(entry)} .*?(?=^## |\Z)", text, flags=re.M | re.S)
    return m.group(0) if m else ""


def registered_facts(claims: Claims) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for name, (digest, source) in REGISTERED_DIGESTS.items():
        text = (ROOT / source).read_text(encoding="utf-8")
        claims.check(f"digest.{name}.registered_in_source", digest in text, source)
        out[name] = {"sha256": digest, "registered_in": source}
    # Amendment R5 1 (b): the RC script checks exactly these values.
    rc = module_string_constants(RC_SCRIPT)
    for name, constant in RC_CONSTANTS.items():
        claims.check(
            f"R5.{name}.equals_{RC_SCRIPT}:{constant}",
            rc.get(constant) == REGISTERED_DIGESTS[name][0],
            str(rc.get(constant)),
        )
    # Amendment R6 1: each entry R-149 moved keeps its pre-rename value (R5 1's), registered in its
    # source, and both values of the pair are in the register's R-149.
    entry = register_entry(REGISTER_ENTRY_R6)
    claims.check(f"R6.register_has_{REGISTER_ENTRY_R6}", bool(entry), REGISTER)
    for name, (digest, source) in REGISTERED_PRE_RENAME.items():
        text = (ROOT / source).read_text(encoding="utf-8")
        claims.check(f"digest.{name}.registered_pre_rename_in_source", digest in text, source)
        for value in (REGISTERED_DIGESTS[name][0], digest):
            claims.check(f"R6.{name}.{value[:8]}_in_{REGISTER_ENTRY_R6}", value in entry, REGISTER)
        out[name]["registered_pre_rename"] = {"sha256": digest, "registered_in": source}
    # Amendment R5 1 (c, d): each moved entry keeps its v1 value, registered in its source, and
    # both values of the R-148 pair (the pre-rename value and the v1 value) are in the register's
    # R-148.
    entry = register_entry(REGISTER_ENTRY)
    claims.check(f"R5.register_has_{REGISTER_ENTRY}", bool(entry), REGISTER)
    for name, (digest, source) in REGISTERED_V1.items():
        text = (ROOT / source).read_text(encoding="utf-8")
        claims.check(f"digest.{name}.registered_v1_in_source", digest in text, source)
        for value in (REGISTERED_PRE_RENAME[name][0], digest):
            claims.check(f"R5.{name}.{value[:8]}_in_{REGISTER_ENTRY}", value in entry, REGISTER)
        out[name]["registered_v1"] = {"sha256": digest, "registered_in": source}
    lock = sha256_file("requirements.lock")
    claims.check(
        "A40.lock_unchanged", lock == REGISTERED_DIGESTS["requirements_lock_sha256"][0], lock
    )
    t07 = json.loads((ROOT / REGISTERED_DIGESTS["requirements_lock_sha256"][1]).read_text())
    claims.check(
        "A40.lock_is_t07_environment_lock",
        t07["inputs"]["environment_lock_hash"] == lock,
        t07["inputs"]["environment_lock_hash"],
    )
    starts = sha256_file("benchmarks/t06/ensemble/starts-nominal-v1.json")
    claims.check(
        "digest.starts_file_bytes",
        starts == REGISTERED_DIGESTS["t06_starts_nominal_sha256"][0],
        starts,
    )
    registry = yaml.safe_load((ROOT / "benchmarks" / "registry.yaml").read_text(encoding="utf-8"))
    ens = registry["ensemble"]
    got = {
        "N": ens["N"],
        "S_min": ens["gate"]["S_min"],
        "machine_classes": list(ens["gate"]["machine_classes"]),
    }
    claims.check("V20.gate_as_registered", got == ENSEMBLE_GATE, str(got))
    claims.check(
        "V20.starts_as_registered",
        ens.get("starts_sha256") == REGISTERED_DIGESTS["t06_starts_nominal_sha256"][0],
        str(ens.get("starts_sha256")),
    )
    out["ensemble_gate"] = got
    out["requirements_lock_sha256_now"] = lock
    return out


def closed_forms(claims: Claims) -> dict[str, Any]:
    cp = []
    for x, n, recorded in CP_POINTS:
        v = cp_lower(x, n)
        # The bound is the root of I_p(x, n-x+1) = 0.05; check the residual at 30 digits.
        resid = betainc(x, n - x + 1, 0, v, regularized=True) - mpf("0.05")
        claims.check(f"cp.{x}_of_{n}.root", abs(resid) < mpf("1e-30"), nstr(resid, 5))
        if recorded is not None:
            digits = len(recorded.split(".")[1])
            claims.check(
                f"cp.{x}_of_{n}.equals_recorded",
                abs(v - mpf(recorded)) <= mpf(10) ** (-digits) / 2 + mpf("1e-16"),
                f"{nstr(v, 20)} vs {recorded}",
            )
        cp.append({"x": x, "n": n, "lower_95_one_sided": nstr(v, 20), "recorded": recorded})
    claims.check("cp.threshold_below_point", mpf(cp_lower(418, 440)) < mpf(418) / 440, "")

    alias = []
    for p in ALIAS_PROBES:
        jm = alias_jmax(p)
        # The closed form agrees with the rule itself at the threshold and one past it, and the
        # rule is monotone: once unsupported, unsupported for every larger j up to 400.
        claims.check(f"alias.{p}.at_jmax", alias_direction(p, jm) != "unsupported", str(jm))
        claims.check(f"alias.{p}.past_jmax", alias_direction(p, jm + 1) == "unsupported", str(jm))
        claims.check(
            f"alias.{p}.monotone",
            all(alias_direction(p, j) == "unsupported" for j in range(jm + 1, 401)),
            "",
        )
        alias.append(
            {
                "P_pa": p,
                "j_max": jm,
                "direction_at_j_max": alias_direction(p, jm),
                "first_unsupported_j": jm + 1,
            }
        )
    worst = min(alias_jmax(p) for p in range(P_LO, P_HI + 1, 50))
    best = max(alias_jmax(p) for p in range(P_LO, P_HI + 1, 50))
    claims.check("alias.worst_is_at_125kPa", worst == alias_jmax(125_000) == 74, str(worst))
    claims.check("alias.best_is_at_domain_edges", best == 149, str(best))
    # The registered NET-11 figure (T06 spec F3): S4.P = 1.8e5 Pa shifted to 204 925 Pa means
    # 997 (j + 1) = 24 925, i.e. j = 24, and the rule sends that column down.
    claims.check("alias.net11_position", ALIAS_BASE_PA * 25 == 24_925, "")
    claims.check("alias.net11_goes_down", alias_direction(180_000, 24) == "down", "")
    # Two sanity directions at 1.8e5 Pa quoted in spec §5.4.
    claims.check("alias.180k_j19_up", alias_direction(180_000, 19) == "up", "")
    claims.check("alias.180k_j20_down", alias_direction(180_000, 20) == "down", "")
    return {
        "clopper_pearson": cp,
        "alias_shift": {
            "base_pa": ALIAS_BASE_PA,
            "domain_pa": [P_LO, P_HI],
            "rule": "supported iff 997 (j + 1) <= max(2e5 - P, P - 5e4)",
            "probes": alias,
            "worst_j_max": worst,
            "best_j_max": best,
        },
    }


def dossier(claims: Claims) -> dict[str, Any]:
    for c, d in CANDIDATES.items():
        claims.check(f"dossier.{c}.hard_complete", set(d["hard"]) == set(HARD), "")
        claims.check(f"dossier.{c}.hard_values", set(d["hard"].values()) <= set(HARD_VALUES), "")
        claims.check(f"dossier.{c}.scores_complete", set(d["scores"]) == set(SCORED), "")
        claims.check(
            f"dossier.{c}.scores_range", all(v in (0, 1, 2) for v, _ in d["scores"].values()), ""
        )
    order = rank(CANDIDATES)
    claims.check("A65.recommended_is_top", order[0] == RECOMMENDED, str(order))
    claims.check("A65.runner_up_is_second", order[1] == RUNNER_UP, str(order))
    sens = sensitivity(CANDIDATES)
    # The specification claims (spec §7.4) that no single provisional score moves the top choice;
    # what moves it is a hard criterion (H5 or H1 failing for C1) or Frank naming a group model
    # for another candidate (S1 of that candidate to 2), which the sensitivity rows show.
    moved = [r for r in sens if r["moves_top"]]
    claims.check(
        "A65.only_s1_of_others_moves_top",
        all(r["score"] == "S1" and r["candidate"] != RECOMMENDED for r in moved),
        str([(r["candidate"], r["score"]) for r in moved]),
    )
    claims.check(
        "A65.c2_s1_moves_top", any(r["candidate"] == "C2" and r["score"] == "S1" for r in moved), ""
    )
    without_c1 = {k: v for k, v in CANDIDATES.items() if k != RECOMMENDED}
    claims.check(
        "A65.fallback_if_c1_unselectable", rank(without_c1)[0] == RUNNER_UP, str(rank(without_c1))
    )
    return {
        "hard_criteria": HARD,
        "hard_values": list(HARD_VALUES),
        "scored_criteria": {k: {"criterion": a, "anchors": b} for k, (a, b) in SCORED.items()},
        "tie_break": list(TIE_BREAK),
        "candidates": {
            c: {
                "label": d["label"],
                "hard": d["hard"],
                "scores": {k: {"score": v, "provisional": p} for k, (v, p) in d["scores"].items()},
                "total": total(d["scores"]),
            }
            for c, d in CANDIDATES.items()
        },
        "ranking": order,
        "recommended": RECOMMENDED,
        "runner_up": RUNNER_UP,
        "sensitivity": sens,
    }


# ---------------------------------------------------------------------------------------------
# 5. Amendment R3 (2026-10-01): the facts its rulings quote, read from committed records.
# ---------------------------------------------------------------------------------------------

#: R3 1: K05's registered SYN-001 runs are the `variants` of this file (T08.A45 (i)).
K05_VARIANTS_FILE = "benchmarks/syn001/reference_values.yaml"
K05_VARIANTS_N = 5

#: R3 6: T08.A15's records (T06 A89's case, THM-09 start 2 under `T06-revision-v2`).
A89_RECORDS = {
    "ci-aarch64": (
        "benchmarks/t08/a89/ci-aarch64.json",
        20,
        "3b4a6132d1869de3eb4f94714a11877a0e43b3f0",
    ),
    "ref-x86-64": (
        "benchmarks/t08/a89/ref-x86-64.json",
        1,
        "8128e171f1d48a7340e037f8b4e88ea77741c07b",
    ),
}
A89_RATIO = "2.166302692785393e-05"

#: R3 7: ADR 0006 Amendment 2 — the aarch64 wheel's two unresolved CasADi objects (path -> bytes,
#: sha256), the x86-64 D4 objects absent on aarch64, and Amendment 1's aarch64 copies.
A30 = {"x86_64": "docs/t08-a30/t08-a30-x86_64.json", "aarch64": "docs/t08-a30/t08-a30-aarch64.json"}
AARCH64_NEW_D4 = {
    "casadi/libgfortran-8de1544a.so.5.0.0": (
        5_413_232,
        "f84fe298f615936bd25cf8a41130eaec46ff05ca62f9e2b9a9b8080a0d87e43a",
    ),
    "casadi/libgomp-7eb2fb8b.so.1.0.0": (
        1_194_968,
        "5e688427525a6c3fee9077533941f107b2d61f6e5892439144cfb597e354c681",
    ),
}
X86_D4_ABSENT_ON_AARCH64 = (
    "casadi/libquadmath-828275a7.so.0.0.0",
    "casadi/libmvec-2-583a17db.28.so",
    "casadi/libspral.a",
)
X86_D4_ALSO_ON_AARCH64 = (
    "casadi/libcplex_adaptor.so",
    "casadi/libgurobi_adaptor.so",
    "casadi/libmatlab_ipc.so",
)
AMENDMENT1_AARCH64 = (
    "numpy.libs/libgfortran-daac5196-038a5e3c.so.5.0.0",
    "scipy.libs/libgfortran-daac5196-038a5e3c.so.5.0.0",
    "scipy.libs/libgfortran-daac5196.so.5.0.0",
)

#: R3 8: the C1 pin and T08.A61's reading, against the committed record.
C1_REACTOR = "benchmarks/t08/v19/c1-reactor.json"
C1_IDAES = "benchmarks/t08/v19/c1-idaes.json"
C1_PROVENANCE = "benchmarks/t08/v19/c1-provenance.json"
C1_PIN = "6089593464fc9bc2c0a0cb58e30ad5433ece6332"
C1_TAG = ("v1.1.0", "d78fbfb32aac366ce446cdfce372444803700632")
C1_TAG_TO_PIN_FILES = ["CITATION.cff", "README.md", "src/reactor/archive.py"]
C1_SUITE = {"collected": 72, "passed": 69, "skipped": 3}
C1_SKIP_GUARDS = [
    "tests/test_cp_closure.py:57",
    "tests/test_paper_pipeline.py:115",
    "tests/test_paper_pipeline.py:127",
]
C1_PYMRM = "2.5.0"
C1_SEPARATOR_K_NH3 = "0.0615"  # the vapour-only separator's K_NH3, to 3 significant digits
H4_ROWS = {
    "HP separator, PR, light gases vapour-only": "Y",
    "HP separator, full PR VLE (gases dissolve in liquid NH3)": "N",
}


def _json(rel: str) -> Any:
    return json.loads((ROOT / rel).read_text(encoding="utf-8"))


def amendment_r3(claims: Claims) -> dict[str, Any]:
    out: dict[str, Any] = {}

    # R3 1
    variants = yaml.safe_load((ROOT / K05_VARIANTS_FILE).read_text(encoding="utf-8"))["variants"]
    ids = [str(v["case_id"]) for v in variants]
    claims.check("R3.1.k05_variants", len(ids) == K05_VARIANTS_N, str(ids))
    claims.check("R3.1.k05_variants_distinct", len(set(ids)) == len(ids), str(ids))
    out["a45_k05_variants"] = ids

    # R3 6
    a89: dict[str, Any] = {}
    for label, (rel, n, commit) in A89_RECORDS.items():
        rec = _json(rel)
        reps = rec["repetitions"]
        head = (rec["case"], rec["start"], rec["policy"], rec["label"], rec["assertion"])
        claims.check(
            f"R3.6.{label}.case",
            head == ("THM-09", 2, "T06-revision-v2", label, "T08.A15"),
            str(head),
        )
        claims.check(f"R3.6.{label}.commit", rec["commit"] == commit, rec["commit"])
        claims.check(f"R3.6.{label}.repetitions", len(reps) == n, str(len(reps)))
        claims.check(f"R3.6.{label}.counts", rec["refinement_counts"] == {"1": n}, str(rec))
        ok = all(
            r["outcome"] == "CONVERGED"
            and r["verification"] == "VERIFIED"
            and r["classification"] == "SUCCESS"
            and r["crash"] is None
            and r["refinement_count"] == 1
            and r["refinements"][0].startswith("terminal_refinement(accepted: chord ")
            and repr(r["s3_worst_ratio"]) == A89_RATIO
            and r["s3_worst_ratio"] <= rec["ratio_bound"] == 0.1
            for r in reps
        )
        claims.check(f"R3.6.{label}.every_repetition", ok and rec["all_meet_a89_outcome"], "")
        a89[label] = {"repetitions": n, "commit": commit, "refinement_count": 1}
    out["a89"] = {"s3_worst_ratio": A89_RATIO, "records": a89}

    # R3 7
    inv = {arch: _json(rel) for arch, rel in A30.items()}
    found = {
        arch: {
            f["path"]: f
            for f in doc["findings"]
            if f["distribution"] in ("casadi", "numpy", "scipy")
        }
        for arch, doc in inv.items()
    }
    arm, x86 = found["aarch64"], found["x86_64"]
    claims.check("R3.7.aarch64_pass", inv["aarch64"]["verdict"]["pass"] is True, "")
    claims.check(
        "R3.7.aarch64_lock",
        inv["aarch64"]["lock_sha256"] == REGISTERED_DIGESTS["requirements_lock_sha256"][0],
        inv["aarch64"]["lock_sha256"],
    )
    for path, (size, digest) in AARCH64_NEW_D4.items():
        f = arm.get(path)
        claims.check(
            f"R3.7.new.{path}",
            f is not None
            and (f["bytes"], f["sha256"], f["category"], f["licence"], f["notices"])
            == (size, digest, "unresolved", None, [])
            and f["in_required_closure"] is False
            and f["loaded_by_project"] is False
            and f["dispositioned_by"] in (None, "ADR 0006 Amendment 2")
            and path not in x86,
            str(f),
        )
    for path in X86_D4_ABSENT_ON_AARCH64:
        claims.check(
            f"R3.7.absent.{path}",
            path not in arm and x86.get(path, {}).get("dispositioned_by") == "ADR 0006 D4",
            "",
        )
    for path in X86_D4_ALSO_ON_AARCH64:
        f = arm.get(path, {})
        claims.check(
            f"R3.7.present.{path}",
            f.get("dispositioned_by") == "ADR 0006 D4" and f.get("in_required_closure") is False,
            str(f),
        )
    unresolved_arm = sorted(
        p for p, f in arm.items() if f["distribution"] == "casadi" and f["category"] == "unresolved"
    )
    claims.check(
        "R3.7.aarch64_unresolved_set",
        unresolved_arm == sorted([*AARCH64_NEW_D4, *X86_D4_ALSO_ON_AARCH64]),
        str(unresolved_arm),
    )
    for path in AMENDMENT1_AARCH64:
        f = arm.get(path, {})
        claims.check(
            f"R3.7.amendment1.{path}",
            f.get("licence") == "GPL-3.0-with-GCC-exception"
            and f.get("dispositioned_by") == "ADR 0006 Amendment 1",
            str(f),
        )
    claims.check(
        "R3.7.aarch64_numpy_scipy_no_lgpl",
        all(
            "lgpl" not in inv["aarch64"]["categories_by_distribution"][d]
            and "lgpl" in inv["x86_64"]["categories_by_distribution"][d]
            for d in ("numpy", "scipy")
        ),
        "",
    )
    out["adr0006_amendment2"] = {
        "aarch64_new_unresolved": {
            p: {"bytes": b, "sha256": h} for p, (b, h) in AARCH64_NEW_D4.items()
        },
        "x86_64_d4_absent_on_aarch64": list(X86_D4_ABSENT_ON_AARCH64),
        "amendment1_aarch64_copies": list(AMENDMENT1_AARCH64),
    }

    # R3 8
    rec = _json(C1_REACTOR)
    repo, suite = rec["group_repository"], rec["group_test_suite"]
    claims.check("R3.8.pin", repo["commit"] == C1_PIN and repo["branch"] == "main", repo["commit"])
    claims.check(
        "R3.8.tag",
        (repo["tag"], repo["tag_commit"]) == C1_TAG
        and repo["files_changed_tag_to_commit"] == C1_TAG_TO_PIN_FILES,
        str((repo["tag"], repo["tag_commit"], repo["files_changed_tag_to_commit"])),
    )
    claims.check(
        "R3.8.suite",
        suite["collected"] == C1_SUITE["collected"]
        and suite["counts"] == {"passed": C1_SUITE["passed"], "skipped": C1_SUITE["skipped"]}
        and suite["exit_code"] == 0
        and "failed" not in suite["summary_line"],
        str(suite["counts"]),
    )
    guards = [s.split(": ", 1)[0] for s in suite["skipped"]]
    claims.check("R3.8.skip_guards", guards == C1_SKIP_GUARDS, str(guards))
    claims.check(
        "R3.8.pymrm", rec["environment"]["packages"]["pymrm"] == C1_PYMRM, str(rec["environment"])
    )
    solve = rec["one_1d_solve"]["non_isothermal"]["result"]
    claims.check(
        "R3.8.one_solve",
        solve["status"] == "converged"
        and solve["solve_converged"] is True
        and solve["element_balance_ok"] is True
        and solve["is_isothermal"] is False,
        str({k: solve.get(k) for k in ("status", "element_balance_ok")}),
    )
    nm = rec["no_membrane"]
    starts = [(r["result"]["dt_init_1d"], r["result"]["status"]) for r in nm["isothermal_by_start"]]
    claims.check(
        "R3.8.no_membrane",
        nm["non_isothermal"]["result"]["status"] == "converged"
        and starts == [(1e-06, "failed"), (0.001, "failed"), (0.01, "converged")],
        str(starts),
    )
    idaes = _json(C1_IDAES)
    rows = {r["unit"]: r["representable"] for r in idaes["representability"]}
    claims.check("R3.8.h4_rows", all(rows.get(u) == v for u, v in H4_ROWS.items()), str(rows))
    vo = idaes["pr_flash"]["light_gases_vapour_only"]
    full = idaes["pr_flash"]["full_vle_all_components_both_phases"]
    k_nh3 = vo["separator"]["K_value"]["NH3"]
    claims.check(
        "R3.8.vapour_only_solves",
        vo["separator"]["termination_condition"] == "optimal"
        and vo["reactor_inlet"]["termination_condition"] == "optimal"
        and idaes["loop_skeleton"]["termination_condition"] == "optimal"
        and f"{k_nh3:.3g}" == C1_SEPARATOR_K_NH3,
        str(k_nh3),
    )
    claims.check(
        "R3.8.full_vle_trivial",
        full["separator"].get("trivial_solution") is True
        and full["reactor_inlet"].get("trivial_solution") is True,
        "",
    )
    prov = {f["item"]: f["status"] for f in _json(C1_PROVENANCE)["findings"]}
    claims.check(
        "R3.8.k_nh3_discrepancy_open",
        prov.get("discrepancy: NH3 adsorption constant") == "discrepancy",
        str(prov),
    )
    out["v19"] = {
        "c1_pin": C1_PIN,
        "c1_tag": {"name": C1_TAG[0], "commit": C1_TAG[1], "differs_in": C1_TAG_TO_PIN_FILES},
        "a61_suite": {**C1_SUITE, "failed": 0, "skip_guards": C1_SKIP_GUARDS},
        "pymrm": C1_PYMRM,
        "h4_method": "Peng-Robinson; H2, N2, Ar, CH4 vapour-only (liquid NH3 only)",
        "separator_K_NH3_3sig": C1_SEPARATOR_K_NH3,
    }
    return out


def catalogue(claims: Claims) -> dict[str, Any]:
    text = SPEC.read_text(encoding="utf-8")
    in_spec = re.findall(r"^\| (T08\.A\d\d) \|", text, flags=re.M)
    claims.check(
        "A00.spec_ids_unique",
        len(in_spec) == len(set(in_spec)),
        str(sorted({i for i in in_spec if in_spec.count(i) > 1})),
    )
    claims.check(
        "A00.spec_equals_catalogue",
        set(in_spec) == set(ASSERTIONS),
        f"spec only {sorted(set(in_spec) - set(ASSERTIONS))}; "
        f"catalogue only {sorted(set(ASSERTIONS) - set(in_spec))}",
    )
    claims.check("A00.spec_order", in_spec == sorted(in_spec), "")
    gate_rows = re.findall(r"^\| \*\*(V\d\d)\*\* \|", text, flags=re.M)
    claims.check("A00.one_summary_row_per_gate", gate_rows == list(GATES), str(gate_rows))
    return {k: {"subject": s, "judged_by": j} for k, (s, j) in ASSERTIONS.items()}


def build(claims: Claims) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "generator": "docs/derivations/scripts/t08_reference.py",
        "specification": "docs/derivations/T08-release-spec.md",
        "precision": "mpmath 40 significant digits, written to 20; integers and rationals exact",
        "independence": "imports nothing from process_runtime or benchmarks; reads committed files",
        "registered": {
            "manifests": manifest_facts(claims),
            "harvest_today": harvest_counts(claims),
            **registered_facts(claims),
        },
        "closed_form": closed_forms(claims),
        "dossier": dossier(claims),
        "amendment_r3": amendment_r3(claims),
        "assertions": catalogue(claims),
    }


def dump(data: dict[str, Any]) -> str:
    header = (
        "# Generated by docs/derivations/scripts/t08_reference.py -- do not edit.\n"
        "# Re-derive with --check; regenerate with --emit.\n"
    )
    return header + yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=100)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="re-derive every claim and compare with the committed YAML",
    )
    parser.add_argument("--emit", metavar="PATH", help="write the reference YAML")
    args = parser.parse_args(argv)
    if not args.check and not args.emit:
        parser.error("choose --check and/or --emit PATH")
    claims = Claims()
    text = dump(build(claims))
    for name, ok, detail in claims.results:
        if not ok:
            print(f"FAIL {name}: {detail}")
    print(f"{len(claims.results) - len(claims.failed)} of {len(claims.results)} claims pass")
    if claims.failed:
        return 1
    data = text.encode("utf-8")
    if args.check:
        committed = YAML_PATH.read_bytes() if YAML_PATH.exists() else b""
        same = committed == data
        print(
            f"committed YAML {'equals' if same else 'DIFFERS FROM'} the regenerated bytes "
            f"(sha256 {hashlib.sha256(data).hexdigest()})"
        )
        if not same:
            return 1
    if args.emit:
        path = Path(args.emit)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        print(f"wrote {path} ({len(data)} bytes, sha256 {hashlib.sha256(data).hexdigest()})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
