// Generated by scripts/m06_web_routes.py from the HTTP binding's OPERATIONS rows; do not
// edit. Regenerate with `python scripts/m06_web_routes.py --write` (a test runs --check).

const freeze = (value) => {
  if (value !== null && typeof value === "object") {
    for (const member of Object.values(value)) freeze(member);
    Object.freeze(value);
  }
  return value;
};

export const ROUTES = freeze({
  "artifact_bytes": {
    "members": [
      "artifact_id"
    ],
    "path": "/v1/artifacts/{artifact_id}/raw",
    "path_params": [
      "artifact_id"
    ],
    "right": "read",
    "verb": "GET"
  },
  "cancel_job": {
    "members": [
      "job_id"
    ],
    "path": "/v1/jobs/{job_id}/cancel",
    "path_params": [
      "job_id"
    ],
    "right": "execute",
    "verb": "POST"
  },
  "commit_change": {
    "members": [
      "author",
      "edits",
      "expected_revision",
      "idempotency_key",
      "new_revision_id",
      "restore_from",
      "task"
    ],
    "path": "/v1/changes",
    "path_params": [],
    "right": "draft",
    "verb": "POST"
  },
  "diff_revisions": {
    "members": [
      "from_revision",
      "to_revision"
    ],
    "path": "/v1/revisions/{from_revision}/diff/{to_revision}",
    "path_params": [
      "from_revision",
      "to_revision"
    ],
    "right": "read",
    "verb": "GET"
  },
  "get_artifact": {
    "members": [
      "artifact_id",
      "cursor",
      "depth",
      "limit",
      "pointer"
    ],
    "path": "/v1/artifacts/{artifact_id}",
    "path_params": [
      "artifact_id"
    ],
    "right": "read",
    "verb": "GET"
  },
  "get_job": {
    "members": [
      "job_id"
    ],
    "path": "/v1/jobs/{job_id}",
    "path_params": [
      "job_id"
    ],
    "right": "read",
    "verb": "GET"
  },
  "get_job_result": {
    "members": [
      "job_id"
    ],
    "path": "/v1/jobs/{job_id}/result",
    "path_params": [
      "job_id"
    ],
    "right": "read",
    "verb": "GET"
  },
  "get_project": {
    "members": [],
    "path": "/v1/project",
    "path_params": [],
    "right": "read",
    "verb": "GET"
  },
  "get_revision": {
    "members": [
      "cursor",
      "depth",
      "limit",
      "pointer",
      "revision_id"
    ],
    "path": "/v1/revisions/{revision_id}",
    "path_params": [
      "revision_id"
    ],
    "right": "read",
    "verb": "GET"
  },
  "inspect_structure": {
    "members": [
      "cursor",
      "depth",
      "limit",
      "pointer",
      "revision_id"
    ],
    "path": "/v1/revisions/{revision_id}/structure",
    "path_params": [
      "revision_id"
    ],
    "right": "read",
    "verb": "GET"
  },
  "list_audit": {
    "members": [
      "cursor",
      "limit",
      "operation",
      "order",
      "principal_id"
    ],
    "path": "/v1/audit",
    "path_params": [],
    "right": "read",
    "verb": "GET"
  },
  "list_job_events": {
    "members": [
      "after_sequence",
      "job_id",
      "limit"
    ],
    "path": "/v1/jobs/{job_id}/events",
    "path_params": [
      "job_id"
    ],
    "right": "read",
    "verb": "GET"
  },
  "list_jobs": {
    "members": [
      "cursor",
      "limit",
      "status"
    ],
    "path": "/v1/jobs",
    "path_params": [],
    "right": "read",
    "verb": "GET"
  },
  "list_models": {
    "members": [],
    "path": "/v1/models",
    "path_params": [],
    "right": "read",
    "verb": "GET"
  },
  "list_revisions": {
    "members": [
      "cursor",
      "limit"
    ],
    "path": "/v1/revisions",
    "path_params": [],
    "right": "read",
    "verb": "GET"
  },
  "preview_change": {
    "members": [
      "author",
      "edits",
      "expected_revision",
      "new_revision_id",
      "restore_from",
      "task"
    ],
    "path": "/v1/changes/preview",
    "path_params": [],
    "right": "read",
    "verb": "POST"
  },
  "submit_job": {
    "members": [
      "body",
      "budgets",
      "idempotency_key",
      "operation"
    ],
    "path": "/v1/jobs",
    "path_params": [],
    "right": "execute",
    "verb": "POST"
  },
  "validate": {
    "members": [
      "revision_id",
      "task"
    ],
    "path": "/v1/revisions/{revision_id}/validate",
    "path_params": [
      "revision_id"
    ],
    "right": "read",
    "verb": "POST"
  },
  "wait_job": {
    "members": [
      "after_sequence",
      "job_id",
      "timeout_s"
    ],
    "path": "/v1/jobs/{job_id}/wait",
    "path_params": [
      "job_id"
    ],
    "right": "read",
    "verb": "GET"
  }
});
