"""M06 (design note §5.3): generate the web shell's route table from the HTTP binding's rows.

`apps/web/js/routes.js` is the only place the shell learns a verb, a path or a request member:
`api.js` builds every URL from it. It is generated from `bindings.http.HTTP_OPERATIONS` (the
`OPERATIONS` rows whose transports include `http`), keys sorted, one entry per row:
`{verb, path, right, path_params, members}` — `path_params` the `{name}` segments of the path in
order, `members` every member of the request schema (a top-level `$ref` followed into the
published schema it names), sorted. Nothing in it is written by hand.

Usage: `python scripts/m06_web_routes.py --write` rewrites the file; `--check` exits 1 when the
committed file differs from what the rows generate (a test runs it).
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Final

from openflowsheet.application.bindings.http import HTTP_OPERATIONS
from openflowsheet.application.operations import Operation
from openflowsheet.application.types import published_schemas

ROOT: Final[Path] = Path(__file__).resolve().parents[1]
TARGET: Final[Path] = ROOT / "apps" / "web" / "js" / "routes.js"
HEADER: Final[str] = (
    "// Generated by scripts/m06_web_routes.py from the HTTP binding's OPERATIONS rows; do not\n"
    "// edit. Regenerate with `python scripts/m06_web_routes.py --write` (a test runs --check).\n"
)
_PATH_PARAMETER: Final[re.Pattern[str]] = re.compile(r"\{([a-z_]+)\}")


def _resolve(schema: Mapping[str, Any]) -> Mapping[str, Any]:
    """`schema`, or the published schema node its top-level `$ref` names."""
    reference = schema.get("$ref")
    if not isinstance(reference, str):
        return schema
    base, _, fragment = reference.partition("#")
    node: Any = published_schemas()[base]
    for token in [t for t in fragment.split("/") if t]:
        node = node[token.replace("~1", "/").replace("~0", "~")]
    assert isinstance(node, Mapping)
    return node


def route(operation: Operation) -> dict[str, Any]:
    assert operation.http is not None
    verb, path = operation.http
    members = sorted(_resolve(operation.request_schema).get("properties", {}))
    path_params = _PATH_PARAMETER.findall(path)
    assert set(path_params) <= set(members), operation.name
    return {
        "verb": verb,
        "path": path,
        "right": operation.right,
        "path_params": path_params,
        "members": members,
    }


def render() -> str:
    table = {operation.name: route(operation) for operation in HTTP_OPERATIONS}
    body = json.dumps(table, indent=2, sort_keys=True, ensure_ascii=False)
    return (
        HEADER
        + "\n"
        + "const freeze = (value) => {\n"
        + '  if (value !== null && typeof value === "object") {\n'
        + "    for (const member of Object.values(value)) freeze(member);\n"
        + "    Object.freeze(value);\n"
        + "  }\n"
        + "  return value;\n"
        + "};\n"
        + "\n"
        + f"export const ROUTES = freeze({body});\n"
    )


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    arguments = parser.parse_args(argv)
    text = render()
    if arguments.write:
        TARGET.write_text(text, encoding="utf-8")
        print(f"wrote {TARGET.relative_to(ROOT)} ({len(HTTP_OPERATIONS)} routes)")
        return 0
    current = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else None
    if current != text:
        print(f"{TARGET.relative_to(ROOT)} is stale: run scripts/m06_web_routes.py --write")
        return 1
    print(f"{TARGET.relative_to(ROOT)} matches the HTTP rows ({len(HTTP_OPERATIONS)} routes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
